export const ENGLISH_SPEAKING_GUIDE_SENTENCES = [
  { sentence: 'Good morning. How are you today?', translation: 'Chào buổi sáng. Hôm nay bạn thế nào?', topic: 'Greetings', level: 'A1' },
  { sentence: 'I am fine, thank you.', translation: 'Tôi khỏe, cảm ơn bạn.', topic: 'Greetings', level: 'A1' },
  { sentence: 'Nice to meet you.', translation: 'Rất vui được gặp bạn.', topic: 'Greetings', level: 'A1' },
  { sentence: 'What is your name?', translation: 'Tên của bạn là gì?', topic: 'Greetings', level: 'A1' },
  { sentence: 'My name is Anna.', translation: 'Tên tôi là Anna.', topic: 'Greetings', level: 'A1' },
  { sentence: 'Where are you from?', translation: 'Bạn đến từ đâu?', topic: 'Greetings', level: 'A1' },
  { sentence: 'I am from Vietnam.', translation: 'Tôi đến từ Việt Nam.', topic: 'Greetings', level: 'A1' },
  { sentence: 'How old are you?', translation: 'Bạn bao nhiêu tuổi?', topic: 'Greetings', level: 'A1' },
  { sentence: 'I am twenty years old.', translation: 'Tôi hai mươi tuổi.', topic: 'Greetings', level: 'A1' },
  { sentence: 'See you later.', translation: 'Hẹn gặp lại sau.', topic: 'Greetings', level: 'A1' },
  { sentence: 'I wake up at six every day.', translation: 'Tôi thức dậy lúc sáu giờ mỗi ngày.', topic: 'Daily Life', level: 'A1' },
  { sentence: 'I brush my teeth after breakfast.', translation: 'Tôi đánh răng sau bữa sáng.', topic: 'Daily Life', level: 'A1' },
  { sentence: 'I go to work by bus.', translation: 'Tôi đi làm bằng xe buýt.', topic: 'Daily Life', level: 'A1' },
  { sentence: 'She studies English in the evening.', translation: 'Cô ấy học tiếng Anh vào buổi tối.', topic: 'Daily Life', level: 'A1' },
  { sentence: 'We have dinner at home.', translation: 'Chúng tôi ăn tối ở nhà.', topic: 'Daily Life', level: 'A1' },
  { sentence: 'He usually goes to bed at ten.', translation: 'Anh ấy thường đi ngủ lúc mười giờ.', topic: 'Daily Life', level: 'A1' },
  { sentence: 'I drink coffee in the morning.', translation: 'Tôi uống cà phê vào buổi sáng.', topic: 'Daily Life', level: 'A1' },
  { sentence: 'They walk to school together.', translation: 'Họ đi bộ đến trường cùng nhau.', topic: 'Daily Life', level: 'A1' },
  { sentence: 'My mother cooks very well.', translation: 'Mẹ tôi nấu ăn rất ngon.', topic: 'Daily Life', level: 'A1' },
  { sentence: 'We clean the house on Sunday.', translation: 'Chúng tôi dọn nhà vào Chủ nhật.', topic: 'Daily Life', level: 'A1' },
  { sentence: 'I would like a bowl of soup.', translation: 'Tôi muốn một bát súp.', topic: 'Food', level: 'A1' },
  { sentence: 'Can I have a glass of water?', translation: 'Tôi có thể lấy một ly nước không?', topic: 'Food', level: 'A1' },
  { sentence: 'This sandwich tastes really good.', translation: 'Bánh sandwich này thật sự ngon.', topic: 'Food', level: 'A1' },
  { sentence: 'Do you want some more rice?', translation: 'Bạn có muốn thêm cơm không?', topic: 'Food', level: 'A1' },
  { sentence: 'I am allergic to peanuts.', translation: 'Tôi bị dị ứng với đậu phộng.', topic: 'Food', level: 'A2' },
  { sentence: 'Please make it less spicy.', translation: 'Làm ơn nấu ít cay hơn.', topic: 'Food', level: 'A2' },
  { sentence: 'We ordered chicken and salad.', translation: 'Chúng tôi đã gọi gà và salad.', topic: 'Food', level: 'A1' },
  { sentence: 'How much is this coffee?', translation: 'Cà phê này giá bao nhiêu?', topic: 'Food', level: 'A1' },
  { sentence: 'The food is fresh and delicious.', translation: 'Món ăn tươi và ngon.', topic: 'Food', level: 'A1' },
  { sentence: 'I need a table for two, please.', translation: 'Tôi cần một bàn cho hai người.', topic: 'Food', level: 'A2' },
  { sentence: 'Turn left at the next corner.', translation: 'Rẽ trái ở góc tiếp theo.', topic: 'Travel', level: 'A1' },
  { sentence: 'How can I get to the station?', translation: 'Tôi có thể đến nhà ga bằng cách nào?', topic: 'Travel', level: 'A1' },
  { sentence: 'I would like to buy a ticket.', translation: 'Tôi muốn mua một vé.', topic: 'Travel', level: 'A1' },
  { sentence: 'What time does the train leave?', translation: 'Tàu rời ga lúc mấy giờ?', topic: 'Travel', level: 'A1' },
  { sentence: 'My flight was delayed for two hours.', translation: 'Chuyến bay của tôi bị hoãn hai tiếng.', topic: 'Travel', level: 'A2' },
  { sentence: 'Could you show me the way?', translation: 'Bạn có thể chỉ đường cho tôi không?', topic: 'Travel', level: 'A1' },
  { sentence: 'I am looking for a cheap hotel.', translation: 'Tôi đang tìm một khách sạn giá rẻ.', topic: 'Travel', level: 'A2' },
  { sentence: 'Please help me with my luggage.', translation: 'Làm ơn giúp tôi với hành lý.', topic: 'Travel', level: 'A1' },
  { sentence: 'The museum is across the street.', translation: 'Bảo tàng ở phía bên kia đường.', topic: 'Travel', level: 'A1' },
  { sentence: 'We took many photos on the trip.', translation: 'Chúng tôi chụp nhiều ảnh trong chuyến đi.', topic: 'Travel', level: 'A1' },
  { sentence: 'I have a meeting at nine o clock.', translation: 'Tôi có cuộc họp lúc chín giờ.', topic: 'Work', level: 'A1' },
  { sentence: 'Please send me the report by email.', translation: 'Làm ơn gửi báo cáo cho tôi qua email.', topic: 'Work', level: 'A2' },
  { sentence: 'She works in the sales department.', translation: 'Cô ấy làm việc ở phòng kinh doanh.', topic: 'Work', level: 'A2' },
  { sentence: 'Let us discuss this problem tomorrow.', translation: 'Hãy thảo luận vấn đề này vào ngày mai.', topic: 'Work', level: 'A2' },
  { sentence: 'I need more time to finish this task.', translation: 'Tôi cần thêm thời gian để hoàn thành nhiệm vụ này.', topic: 'Work', level: 'A2' },
  { sentence: 'Can you join the online meeting?', translation: 'Bạn có thể tham gia cuộc họp trực tuyến không?', topic: 'Work', level: 'A2' },
  { sentence: 'Our team reached the monthly goal.', translation: 'Đội của chúng tôi đã đạt mục tiêu hàng tháng.', topic: 'Work', level: 'A2' },
  { sentence: 'He is preparing a short presentation.', translation: 'Anh ấy đang chuẩn bị một bài thuyết trình ngắn.', topic: 'Work', level: 'A2' },
  { sentence: 'Please check the final version carefully.', translation: 'Làm ơn kiểm tra kỹ phiên bản cuối cùng.', topic: 'Work', level: 'A2' },
  { sentence: 'We need to improve customer service.', translation: 'Chúng tôi cần cải thiện dịch vụ khách hàng.', topic: 'Work', level: 'B1' },
  { sentence: 'I am learning new words every day.', translation: 'Tôi đang học từ mới mỗi ngày.', topic: 'Study', level: 'A1' },
  { sentence: 'She practices speaking with her friends.', translation: 'Cô ấy luyện nói với bạn bè.', topic: 'Study', level: 'A2' },
  { sentence: 'This lesson is easier than the last one.', translation: 'Bài học này dễ hơn bài trước.', topic: 'Study', level: 'A2' },
  { sentence: 'Can you explain this grammar point again?', translation: 'Bạn có thể giải thích lại điểm ngữ pháp này không?', topic: 'Study', level: 'A2' },
  { sentence: 'I forgot to bring my notebook.', translation: 'Tôi quên mang theo quyển vở.', topic: 'Study', level: 'A1' },
  { sentence: 'We review the vocabulary before the test.', translation: 'Chúng tôi ôn lại từ vựng trước bài kiểm tra.', topic: 'Study', level: 'A2' },
  { sentence: 'The teacher gave us useful feedback.', translation: 'Giáo viên đã cho chúng tôi phản hồi hữu ích.', topic: 'Study', level: 'A2' },
  { sentence: 'I need to concentrate on my pronunciation.', translation: 'Tôi cần tập trung vào phát âm của mình.', topic: 'Study', level: 'B1' },
  { sentence: 'He asked an interesting question in class.', translation: 'Anh ấy đã hỏi một câu thú vị trong lớp.', topic: 'Study', level: 'A2' },
  { sentence: 'I want to speak more naturally.', translation: 'Tôi muốn nói tự nhiên hơn.', topic: 'Study', level: 'B1' },
  { sentence: 'My family is having dinner together.', translation: 'Gia đình tôi đang ăn tối cùng nhau.', topic: 'Family', level: 'A1' },
  { sentence: 'My sister is younger than me.', translation: 'Em gái tôi nhỏ tuổi hơn tôi.', topic: 'Family', level: 'A1' },
  { sentence: 'We visit our grandparents every month.', translation: 'Chúng tôi thăm ông bà mỗi tháng.', topic: 'Family', level: 'A1' },
  { sentence: 'His father works in a hospital.', translation: 'Bố của anh ấy làm việc trong bệnh viện.', topic: 'Family', level: 'A1' },
  { sentence: 'They moved to a new apartment last year.', translation: 'Họ đã chuyển đến một căn hộ mới năm ngoái.', topic: 'Family', level: 'A2' },
  { sentence: 'My brother likes playing soccer after school.', translation: 'Anh trai tôi thích chơi bóng đá sau giờ học.', topic: 'Family', level: 'A1' },
  { sentence: 'We are planning a family trip this summer.', translation: 'Chúng tôi đang lên kế hoạch cho chuyến du lịch gia đình vào mùa hè này.', topic: 'Family', level: 'A2' },
  { sentence: 'Her baby started walking last week.', translation: 'Em bé của cô ấy bắt đầu biết đi vào tuần trước.', topic: 'Family', level: 'A2' },
  { sentence: 'I call my parents every evening.', translation: 'Tôi gọi cho bố mẹ mỗi buổi tối.', topic: 'Family', level: 'A1' },
  { sentence: 'Our home feels warm and peaceful.', translation: 'Ngôi nhà của chúng tôi cảm thấy ấm áp và yên bình.', topic: 'Family', level: 'A2' },
  { sentence: 'I have a headache and a sore throat.', translation: 'Tôi bị đau đầu và đau họng.', topic: 'Health', level: 'A2' },
  { sentence: 'You should drink more water.', translation: 'Bạn nên uống nhiều nước hơn.', topic: 'Health', level: 'A1' },
  { sentence: 'She needs to see a doctor.', translation: 'Cô ấy cần gặp bác sĩ.', topic: 'Health', level: 'A1' },
  { sentence: 'I feel much better today.', translation: 'Hôm nay tôi cảm thấy tốt hơn nhiều.', topic: 'Health', level: 'A1' },
  { sentence: 'Please take this medicine after lunch.', translation: 'Làm ơn uống thuốc này sau bữa trưa.', topic: 'Health', level: 'A2' },
  { sentence: 'Regular exercise is good for your health.', translation: 'Tập thể dục thường xuyên tốt cho sức khỏe của bạn.', topic: 'Health', level: 'A2' },
  { sentence: 'He injured his knee during the game.', translation: 'Anh ấy bị thương đầu gối trong trận đấu.', topic: 'Health', level: 'B1' },
  { sentence: 'I am trying to sleep earlier these days.', translation: 'Dạo này tôi đang cố gắng ngủ sớm hơn.', topic: 'Health', level: 'A2' },
  { sentence: 'The nurse checked my temperature.', translation: 'Y tá đã kiểm tra nhiệt độ của tôi.', topic: 'Health', level: 'A2' },
  { sentence: 'Deep breathing helps me relax.', translation: 'Hít thở sâu giúp tôi thư giãn.', topic: 'Health', level: 'A2' },
  { sentence: 'The weather is sunny and warm today.', translation: 'Hôm nay thời tiết nắng và ấm.', topic: 'Weather', level: 'A1' },
  { sentence: 'It might rain this afternoon.', translation: 'Chiều nay có thể trời sẽ mưa.', topic: 'Weather', level: 'A2' },
  { sentence: 'Do not forget your umbrella.', translation: 'Đừng quên ô của bạn.', topic: 'Weather', level: 'A1' },
  { sentence: 'The wind is very strong near the beach.', translation: 'Gió rất mạnh gần bãi biển.', topic: 'Weather', level: 'A2' },
  { sentence: 'Winter is colder than autumn.', translation: 'Mùa đông lạnh hơn mùa thu.', topic: 'Weather', level: 'A1' },
  { sentence: 'The sky became dark very quickly.', translation: 'Bầu trời tối đi rất nhanh.', topic: 'Weather', level: 'A2' },
  { sentence: 'It was too hot to walk outside.', translation: 'Trời quá nóng để đi bộ bên ngoài.', topic: 'Weather', level: 'A2' },
  { sentence: 'We enjoyed the cool evening breeze.', translation: 'Chúng tôi thích làn gió mát buổi tối.', topic: 'Weather', level: 'B1' },
  { sentence: 'The forecast says it will be cloudy tomorrow.', translation: 'Dự báo nói rằng ngày mai trời sẽ nhiều mây.', topic: 'Weather', level: 'B1' },
  { sentence: 'I love the sound of rain at night.', translation: 'Tôi yêu âm thanh của mưa vào ban đêm.', topic: 'Weather', level: 'A2' },
  { sentence: 'Could you speak a little more slowly?', translation: 'Bạn có thể nói chậm hơn một chút không?', topic: 'Conversation', level: 'A2' },
  { sentence: 'I did not catch the last word.', translation: 'Tôi đã không nghe rõ từ cuối cùng.', topic: 'Conversation', level: 'A2' },
  { sentence: 'Can you repeat that, please?', translation: 'Bạn có thể lặp lại điều đó được không?', topic: 'Conversation', level: 'A1' },
  { sentence: 'That sounds like a great idea.', translation: 'Điều đó nghe có vẻ là một ý hay.', topic: 'Conversation', level: 'A2' },
  { sentence: 'I agree with you on this point.', translation: 'Tôi đồng ý với bạn ở điểm này.', topic: 'Conversation', level: 'B1' },
  { sentence: 'Let me think about it for a moment.', translation: 'Để tôi nghĩ về điều đó một lát.', topic: 'Conversation', level: 'A2' },
  { sentence: 'I am not sure, but I will try.', translation: 'Tôi không chắc, nhưng tôi sẽ thử.', topic: 'Conversation', level: 'A2' },
  { sentence: 'What do you mean by that?', translation: 'Bạn có ý gì khi nói vậy?', topic: 'Conversation', level: 'A2' },
  { sentence: 'Please give me an example sentence.', translation: 'Làm ơn cho tôi một câu ví dụ.', topic: 'Conversation', level: 'A2' },
  { sentence: 'Your pronunciation is getting better.', translation: 'Phát âm của bạn đang tốt hơn.', topic: 'Conversation', level: 'A2' },
]
