// ─── SOUND LIBRARY (48 phonemes) ─────────────────────────────────────────
// Mirrors ELSA Speak's Sound Library structure

export const SOUNDS = [
  // ════════════════════════════════════════════════════════════
  // VOWELS — Single Vowels (Monophthongs) · 14 sounds
  // ════════════════════════════════════════════════════════════
  { id:'EE',  label:'EE',  ipa:'iː', type:'vowel', group:'Single Vowels',
    color:'bg-red-700',     grad:'from-red-700 to-red-900',       hard:false,
    tip:'Kéo hai góc môi sang ngang, lưỡi cao và căng về phía trước miệng',
    words:[
      {word:'bee',   meaning:'con ong',     emoji:'🐝'},
      {word:'tree',  meaning:'cây',         emoji:'🌳'},
      {word:'feet',  meaning:'bàn chân',    emoji:'🦶'},
      {word:'sleep', meaning:'ngủ',         emoji:'😴'},
    ]},
  { id:'IH',  label:'IH',  ipa:'ɪ',  type:'vowel', group:'Single Vowels',
    color:'bg-pink-600',    grad:'from-pink-600 to-pink-800',      hard:false,
    tip:'Âm /i/ ngắn — lưỡi cao nhưng miệng thư giãn hơn EE, KHÔNG kéo căng môi',
    words:[
      {word:'fish',  meaning:'cá',          emoji:'🐟'},
      {word:'sit',   meaning:'ngồi',        emoji:'🪑'},
      {word:'bit',   meaning:'miếng nhỏ',   emoji:'🧩'},
      {word:'quick', meaning:'nhanh',       emoji:'⚡'},
    ]},
  { id:'EH',  label:'EH',  ipa:'ɛ',  type:'vowel', group:'Single Vowels',
    color:'bg-purple-700',  grad:'from-purple-700 to-purple-900',  hard:false,
    tip:'Âm "e" ngắn — miệng hé vừa, lưỡi giữa. Khác EE: không kéo môi',
    words:[
      {word:'red',    meaning:'màu đỏ',     emoji:'🔴'},
      {word:'bed',    meaning:'cái giường', emoji:'🛏️'},
      {word:'egg',    meaning:'quả trứng',  emoji:'🥚'},
      {word:'friend', meaning:'bạn bè',     emoji:'🤝'},
    ]},
  { id:'AA',  label:'AA',  ipa:'æ',  type:'vowel', group:'Single Vowels',
    color:'bg-indigo-700',  grad:'from-indigo-700 to-indigo-900',  hard:true,
    tip:'Mở miệng RỘNG hơn EH, kéo về phía trước — "ê-a" kết hợp nhanh. Khó với người Việt!',
    words:[
      {word:'cat',  meaning:'con mèo',  emoji:'🐱'},
      {word:'bag',  meaning:'cái túi',  emoji:'👜'},
      {word:'hand', meaning:'bàn tay',  emoji:'✋'},
      {word:'black',meaning:'màu đen',  emoji:'⬛'},
    ]},
  { id:'UH',  label:'UH',  ipa:'ʌ',  type:'vowel', group:'Single Vowels',
    color:'bg-teal-600',    grad:'from-teal-600 to-teal-800',      hard:true,
    tip:'Giống "ă" tiếng Việt — miệng mở vừa, lưỡi giữa-thấp. KHÔNG phải "ơ" hay "a"',
    words:[
      {word:'cup',  meaning:'cái tách', emoji:'☕'},
      {word:'bus',  meaning:'xe buýt',  emoji:'🚌'},
      {word:'duck', meaning:'con vịt',  emoji:'🦆'},
      {word:'run',  meaning:'chạy',     emoji:'🏃'},
    ]},
  { id:'uh',  label:'uh',  ipa:'ə',  type:'vowel', group:'Single Vowels',
    color:'bg-blue-700',    grad:'from-blue-700 to-blue-900',      hard:false,
    tip:'Schwa — âm trung hòa nhất, miệng HOÀN TOÀN thư giãn. Âm phổ biến nhất trong tiếng Anh!',
    words:[
      {word:'about',  meaning:'về',         emoji:'💭'},
      {word:'today',  meaning:'hôm nay',    emoji:'📅'},
      {word:'problem',meaning:'vấn đề',     emoji:'🤔'},
      {word:'banana', meaning:'chuối',      emoji:'🍌'},
    ]},
  { id:'ER',  label:'ER',  ipa:'ɜː', type:'vowel', group:'Single Vowels',
    color:'bg-fuchsia-600', grad:'from-fuchsia-600 to-fuchsia-800',hard:true,
    tip:'Môi tròn nhẹ, lưỡi giữa không chạm đâu, cuộn ra sau (giọng Mỹ). Khác "ơ" Việt: cuộn lưỡi!',
    words:[
      {word:'bird', meaning:'con chim',  emoji:'🐦'},
      {word:'word', meaning:'từ',        emoji:'📝'},
      {word:'learn',meaning:'học',       emoji:'📚'},
      {word:'turn', meaning:'quay lại',  emoji:'🔄'},
    ]},
  { id:'OO',  label:'OO',  ipa:'uː', type:'vowel', group:'Single Vowels',
    color:'bg-cyan-600',    grad:'from-cyan-600 to-cyan-800',      hard:false,
    tip:'Âm "u" dài — môi tròn căng, đẩy ra phía trước. Kéo dài hơn âm "u" tiếng Việt',
    words:[
      {word:'food',  meaning:'thức ăn',     emoji:'🍜'},
      {word:'moon',  meaning:'mặt trăng',   emoji:'🌙'},
      {word:'school',meaning:'trường học',  emoji:'🏫'},
      {word:'blue',  meaning:'màu xanh dương',emoji:'🔵'},
    ]},
  { id:'U',   label:'U',   ipa:'ʊ',  type:'vowel', group:'Single Vowels',
    color:'bg-green-700',   grad:'from-green-700 to-green-900',    hard:true,
    tip:'Âm "u" NGẮN — môi tròn nhẹ, KHÔNG căng. Khác OO: ngắn hơn và tối hơn',
    words:[
      {word:'book', meaning:'cuốn sách',emoji:'📖'},
      {word:'good', meaning:'tốt',      emoji:'👍'},
      {word:'look', meaning:'nhìn',     emoji:'👀'},
      {word:'put',  meaning:'đặt',      emoji:'👇'},
    ]},
  { id:'AW',  label:'AW',  ipa:'ɔː', type:'vowel', group:'Single Vowels',
    color:'bg-amber-600',   grad:'from-amber-600 to-amber-800',    hard:false,
    tip:'Môi tròn vừa, miệng mở. Giống "o" trong "Ông" nhưng dài hơn',
    words:[
      {word:'call',  meaning:'gọi',     emoji:'📞'},
      {word:'ball',  meaning:'quả bóng',emoji:'⚽'},
      {word:'water', meaning:'nước',    emoji:'💧'},
      {word:'small', meaning:'nhỏ',     emoji:'🔹'},
    ]},
  { id:'AH',  label:'AH',  ipa:'ɑː', type:'vowel', group:'Single Vowels',
    color:'bg-orange-600',  grad:'from-orange-600 to-orange-800',  hard:false,
    tip:'Mở miệng RỘNG nhất, lưỡi thấp phía sau. Giống "a" trong "cha"',
    words:[
      {word:'hot',    meaning:'nóng',   emoji:'🔥'},
      {word:'stop',   meaning:'dừng',   emoji:'🛑'},
      {word:'clock',  meaning:'đồng hồ',emoji:'🕐'},
      {word:'dollar', meaning:'đô la',  emoji:'💵'},
    ]},
  { id:'O',   label:'O',   ipa:'oʊ', type:'vowel', group:'Single Vowels',
    color:'bg-red-600',     grad:'from-red-600 to-red-800',        hard:false,
    tip:'Bắt đầu "o" rồi trượt sang "u" nhẹ — diphthong ngắn. Không phải "ô" đơn',
    words:[
      {word:'go',   meaning:'đi',        emoji:'🏃'},
      {word:'home', meaning:'nhà',       emoji:'🏠'},
      {word:'road', meaning:'con đường', emoji:'🛣️'},
      {word:'cold', meaning:'lạnh',      emoji:'🥶'},
    ]},
  { id:'E',   label:'E',   ipa:'iː', type:'vowel', group:'Single Vowels',
    color:'bg-emerald-600', grad:'from-emerald-600 to-emerald-800',hard:false,
    tip:'Âm /i/ trong các từ kết thúc bằng -y, -ey, -ie — nhẹ và ngắn hơn EE',
    words:[
      {word:'happy',  meaning:'vui vẻ',    emoji:'😊'},
      {word:'city',   meaning:'thành phố', emoji:'🏙️'},
      {word:'very',   meaning:'rất',       emoji:'💪'},
      {word:'funny',  meaning:'buồn cười', emoji:'😄'},
    ]},
  { id:'A',   label:'A',   ipa:'eɪ', type:'vowel', group:'Single Vowels',
    color:'bg-blue-600',    grad:'from-blue-600 to-blue-800',      hard:false,
    tip:'Tên chữ cái A — bắt đầu "e" trượt lên "i". Giống EY nhưng trong pattern chữ a-e',
    words:[
      {word:'name',  meaning:'tên',           emoji:'🏷️'},
      {word:'face',  meaning:'khuôn mặt',     emoji:'😊'},
      {word:'say',   meaning:'nói',           emoji:'💬'},
      {word:'place', meaning:'địa điểm',      emoji:'📍'},
    ]},

  // ════════════════════════════════════════════════════════════
  // VOWELS — Vowel Combinations (Diphthongs) · 9 sounds
  // ════════════════════════════════════════════════════════════
  { id:'EY',  label:'EY',  ipa:'eɪ', type:'vowel', group:'Diphthongs',
    color:'bg-violet-600',  grad:'from-violet-600 to-violet-800',  hard:false,
    tip:'Bắt đầu "e" rồi trượt lên "i" — như trong "say, day"',
    words:[
      {word:'say',    meaning:'nói',        emoji:'💬'},
      {word:'great',  meaning:'tuyệt vời',  emoji:'🌟'},
      {word:'make',   meaning:'làm',        emoji:'🔨'},
      {word:'table',  meaning:'cái bàn',    emoji:'🪑'},
    ]},
  { id:'ai',  label:'ai',  ipa:'aɪ', type:'vowel', group:'Diphthongs',
    color:'bg-teal-600',    grad:'from-teal-600 to-teal-800',      hard:false,
    tip:'Từ "a" rộng trượt lên "i" — như "night, like". Không phải "ây" đơn',
    words:[
      {word:'nice',  meaning:'tốt, dễ chịu',emoji:'😊'},
      {word:'bike',  meaning:'xe đạp',     emoji:'🚲'},
      {word:'night', meaning:'đêm',        emoji:'🌙'},
      {word:'right', meaning:'đúng',       emoji:'✅'},
    ]},
  { id:'OY',  label:'OY',  ipa:'ɔɪ', type:'vowel', group:'Diphthongs',
    color:'bg-indigo-600',  grad:'from-indigo-600 to-indigo-800',  hard:false,
    tip:'Từ "ô" tròn trượt lên "i" — như "boy, oil". Giống âm "oi" tiếng Việt',
    words:[
      {word:'boy',    meaning:'con trai',   emoji:'👦'},
      {word:'oil',    meaning:'dầu',        emoji:'🛢️'},
      {word:'voice',  meaning:'giọng nói',  emoji:'🎤'},
      {word:'enjoy',  meaning:'tận hưởng',  emoji:'😄'},
    ]},
  { id:'OH',  label:'OH',  ipa:'oʊ', type:'vowel', group:'Diphthongs',
    color:'bg-pink-600',    grad:'from-pink-600 to-pink-800',      hard:false,
    tip:'Từ "o" trượt sang "u" nhẹ. Đây là "long O" trong tiếng Anh',
    words:[
      {word:'old',   meaning:'già, cũ',  emoji:'👴'},
      {word:'notes', meaning:'ghi chú',  emoji:'📒'},
      {word:'phone', meaning:'điện thoại',emoji:'📱'},
      {word:'open',  meaning:'mở',       emoji:'🚪'},
    ]},
  { id:'OW',  label:'OW',  ipa:'aʊ', type:'vowel', group:'Diphthongs',
    color:'bg-cyan-600',    grad:'from-cyan-600 to-cyan-800',      hard:false,
    tip:'Từ "a" rộng trượt lên "u" — như "now, out". Không phải "ao" tiếng Việt',
    words:[
      {word:'loud',   meaning:'to, ồn ào', emoji:'📢'},
      {word:'now',    meaning:'bây giờ',   emoji:'⏰'},
      {word:'house',  meaning:'ngôi nhà',  emoji:'🏠'},
      {word:'south',  meaning:'phía nam',  emoji:'🧭'},
    ]},
  { id:'AR',  label:'AR',  ipa:'ɑːr',type:'vowel', group:'Diphthongs',
    color:'bg-teal-700',    grad:'from-teal-700 to-teal-900',      hard:false,
    tip:'Âm "a" dài + cuộn lưỡi nhẹ ra sau (giọng Mỹ). Như "car, large"',
    words:[
      {word:'car',   meaning:'xe hơi',  emoji:'🚗'},
      {word:'large', meaning:'to lớn',  emoji:'🐘'},
      {word:'start', meaning:'bắt đầu', emoji:'▶️'},
      {word:'heart', meaning:'trái tim',emoji:'❤️'},
    ]},
  { id:'OR',  label:'OR',  ipa:'ɔːr',type:'vowel', group:'Diphthongs',
    color:'bg-amber-700',   grad:'from-amber-700 to-amber-900',    hard:false,
    tip:'Âm "ô" tròn + cuộn lưỡi. Như "more, door, for"',
    words:[
      {word:'more',  meaning:'thêm',    emoji:'➕'},
      {word:'door',  meaning:'cánh cửa',emoji:'🚪'},
      {word:'story', meaning:'câu chuyện',emoji:'📖'},
      {word:'before',meaning:'trước',   emoji:'⏮️'},
    ]},
  { id:'AIR', label:'AIR', ipa:'ɛər',type:'vowel', group:'Diphthongs',
    color:'bg-orange-600',  grad:'from-orange-600 to-orange-800',  hard:false,
    tip:'Âm "e" + schwa + cuộn lưỡi. Như "where, chair, square"',
    words:[
      {word:'chair',  meaning:'cái ghế',  emoji:'🪑'},
      {word:'where',  meaning:'ở đâu',    emoji:'📍'},
      {word:'there',  meaning:'ở đó',     emoji:'👉'},
      {word:'careful',meaning:'cẩn thận', emoji:'⚠️'},
    ]},
  { id:'EAR', label:'EAR', ipa:'ɪər',type:'vowel', group:'Diphthongs',
    color:'bg-red-500',     grad:'from-red-500 to-red-700',        hard:false,
    tip:'Âm "i" ngắn + schwa + cuộn lưỡi. Như "near, here, hear"',
    words:[
      {word:'near',  meaning:'gần',       emoji:'📏'},
      {word:'here',  meaning:'ở đây',     emoji:'🏠'},
      {word:'hear',  meaning:'nghe',      emoji:'👂'},
      {word:'really',meaning:'thực sự',   emoji:'💯'},
    ]},

  // ════════════════════════════════════════════════════════════
  // CONSONANTS — Plosives · 6 sounds
  // ════════════════════════════════════════════════════════════
  { id:'P',   label:'P',   ipa:'p',  type:'consonant', group:'Plosives',
    color:'bg-fuchsia-600', grad:'from-fuchsia-600 to-fuchsia-800',hard:false,
    tip:'Khép môi hoàn toàn, tích tụ khí rồi bật ra mạnh (aspirated khi đầu từ)',
    words:[
      {word:'pretty', meaning:'xinh đẹp',emoji:'🌸'},
      {word:'plant',  meaning:'cây',     emoji:'🌿'},
      {word:'people', meaning:'người',   emoji:'👥'},
      {word:'stop',   meaning:'dừng',    emoji:'🛑'},
    ]},
  { id:'B',   label:'B',   ipa:'b',  type:'consonant', group:'Plosives',
    color:'bg-blue-600',    grad:'from-blue-600 to-blue-800',      hard:false,
    tip:'Giống P nhưng RUNG HỌng. Bật môi + rung dây thanh âm',
    words:[
      {word:'baby',  meaning:'em bé',    emoji:'👶'},
      {word:'bird',  meaning:'con chim', emoji:'🐦'},
      {word:'book',  meaning:'cuốn sách',emoji:'📖'},
      {word:'big',   meaning:'to lớn',   emoji:'🐘'},
    ]},
  { id:'T',   label:'T',   ipa:'t',  type:'consonant', group:'Plosives',
    color:'bg-emerald-600', grad:'from-emerald-600 to-emerald-800',hard:false,
    tip:'Lưỡi chạm sau răng cửa trên, bật ra. Đầu từ có hơi thở (aspirated)',
    words:[
      {word:'tiny',   meaning:'tí hon',  emoji:'🐜'},
      {word:'turtle', meaning:'rùa',     emoji:'🐢'},
      {word:'table',  meaning:'cái bàn', emoji:'🪑'},
      {word:'time',   meaning:'thời gian',emoji:'⏰'},
    ]},
  { id:'D',   label:'D',   ipa:'d',  type:'consonant', group:'Plosives',
    color:'bg-amber-600',   grad:'from-amber-600 to-amber-800',    hard:false,
    tip:'Giống T nhưng RUNG HỌng. Lưỡi chạm sau răng + rung dây thanh âm',
    words:[
      {word:'dinner', meaning:'bữa tối', emoji:'🍽️'},
      {word:'date',   meaning:'ngày tháng',emoji:'📅'},
      {word:'dog',    meaning:'con chó', emoji:'🐶'},
      {word:'deep',   meaning:'sâu',     emoji:'🌊'},
    ]},
  { id:'K',   label:'K',   ipa:'k',  type:'consonant', group:'Plosives',
    color:'bg-orange-600',  grad:'from-orange-600 to-orange-800',  hard:false,
    tip:'Lưỡi chạm vòm mềm PHÍA SAU miệng, bật ra. Đầu từ có hơi thở',
    words:[
      {word:'candy', meaning:'kẹo',     emoji:'🍬'},
      {word:'cane',  meaning:'gậy',     emoji:'🦯'},
      {word:'kind',  meaning:'tốt bụng',emoji:'💛'},
      {word:'clock', meaning:'đồng hồ', emoji:'🕐'},
    ]},
  { id:'G',   label:'G',   ipa:'g',  type:'consonant', group:'Plosives',
    color:'bg-red-600',     grad:'from-red-600 to-red-800',        hard:false,
    tip:'Giống K nhưng RUNG HỌng. Lưỡi vòm mềm + rung dây thanh âm',
    words:[
      {word:'giggly', meaning:'hay cười',emoji:'😄'},
      {word:'girl',   meaning:'con gái', emoji:'👧'},
      {word:'good',   meaning:'tốt',     emoji:'👍'},
      {word:'big',    meaning:'to lớn',  emoji:'🐘'},
    ]},

  // ════════════════════════════════════════════════════════════
  // CONSONANTS — Nasals · 3 sounds
  // ════════════════════════════════════════════════════════════
  { id:'M',   label:'M',   ipa:'m',  type:'consonant', group:'Nasals',
    color:'bg-purple-600',  grad:'from-purple-600 to-purple-800',  hard:false,
    tip:'Khép môi hoàn toàn, cho khí thoát qua MŨI. Rung cả mũi khi phát âm',
    words:[
      {word:'meek',  meaning:'hiền lành', emoji:'🕊️'},
      {word:'mouse', meaning:'con chuột', emoji:'🐭'},
      {word:'moon',  meaning:'mặt trăng', emoji:'🌙'},
      {word:'name',  meaning:'tên',       emoji:'🏷️'},
    ]},
  { id:'N',   label:'N',   ipa:'n',  type:'consonant', group:'Nasals',
    color:'bg-red-800',     grad:'from-red-800 to-red-900',        hard:false,
    tip:'Lưỡi chạm sau răng cửa trên, khí thoát qua MŨI. Không bật lưỡi',
    words:[
      {word:'new',      meaning:'mới',      emoji:'✨'},
      {word:'necklace', meaning:'vòng cổ',  emoji:'📿'},
      {word:'name',     meaning:'tên',      emoji:'🏷️'},
      {word:'night',    meaning:'đêm',      emoji:'🌙'},
    ]},
  { id:'NG',  label:'NG',  ipa:'ŋ',  type:'consonant', group:'Nasals',
    color:'bg-rose-700',    grad:'from-rose-700 to-rose-900',      hard:false,
    tip:'Lưỡi chạm vòm MỀM phía sau, khí qua mũi. Không có âm "g" riêng lẻ sau /ŋ/',
    words:[
      {word:'ring',     meaning:'chiếc nhẫn',emoji:'💍'},
      {word:'song',     meaning:'bài hát',  emoji:'🎵'},
      {word:'morning',  meaning:'buổi sáng',emoji:'🌅'},
      {word:'learning', meaning:'học hỏi',  emoji:'📚'},
    ]},

  // ════════════════════════════════════════════════════════════
  // CONSONANTS — Fricatives · 9 sounds
  // ════════════════════════════════════════════════════════════
  { id:'F',   label:'F',   ipa:'f',  type:'consonant', group:'Fricatives',
    color:'bg-green-600',   grad:'from-green-600 to-green-800',    hard:false,
    tip:'Răng cửa TRÊN đặt lên môi DƯỚI, thổi khí nhẹ. KHÔNG rung họng',
    words:[
      {word:'furry',  meaning:'có lông xù',emoji:'🐻'},
      {word:'friend', meaning:'bạn bè',    emoji:'🤝'},
      {word:'food',   meaning:'thức ăn',   emoji:'🍜'},
      {word:'phone',  meaning:'điện thoại',emoji:'📱'},
    ]},
  { id:'V',   label:'V',   ipa:'v',  type:'consonant', group:'Fricatives',
    color:'bg-blue-600',    grad:'from-blue-600 to-blue-800',      hard:true,
    tip:'Giống F nhưng RUNG HỌng. Răng trên + môi dưới + rung dây thanh. KHÔNG phải "b"!',
    words:[
      {word:'vital',     meaning:'quan trọng',emoji:'⭐'},
      {word:'vegetable', meaning:'rau củ',   emoji:'🥦'},
      {word:'voice',     meaning:'giọng nói',emoji:'🎤'},
      {word:'very',      meaning:'rất',      emoji:'💪'},
    ]},
  { id:'th',  label:'th',  ipa:'θ',  type:'consonant', group:'Fricatives',
    color:'bg-violet-600',  grad:'from-violet-600 to-violet-800',  hard:true,
    tip:'ĐẶT ĐẦU LƯỠI GIỮA HAI HÀNG RĂNG, thổi khí nhẹ KHÔNG rung họng. Khó nhất!',
    words:[
      {word:'think',    meaning:'suy nghĩ',  emoji:'💭'},
      {word:'three',    meaning:'ba',        emoji:'3️⃣'},
      {word:'bath',     meaning:'tắm',       emoji:'🛁'},
      {word:'earth',    meaning:'trái đất',  emoji:'🌍'},
    ]},
  { id:'TH',  label:'TH',  ipa:'ð',  type:'consonant', group:'Fricatives',
    color:'bg-teal-700',    grad:'from-teal-700 to-teal-900',      hard:true,
    tip:'Giống th nhưng RUNG HỌng. Lưỡi giữa răng + rung dây thanh âm',
    words:[
      {word:'this',    meaning:'cái này',  emoji:'👆'},
      {word:'mother',  meaning:'mẹ',       emoji:'👩'},
      {word:'weather', meaning:'thời tiết',emoji:'⛅'},
      {word:'breathe', meaning:'thở',      emoji:'🫁'},
    ]},
  { id:'S',   label:'S',   ipa:'s',  type:'consonant', group:'Fricatives',
    color:'bg-pink-600',    grad:'from-pink-600 to-pink-800',      hard:false,
    tip:'Đầu lưỡi gần (không chạm) sau răng cửa trên, thổi khí. Không rung họng',
    words:[
      {word:'soft',    meaning:'mềm',      emoji:'🧸'},
      {word:'sweater', meaning:'áo len',   emoji:'🧥'},
      {word:'school',  meaning:'trường',   emoji:'🏫'},
      {word:'sleep',   meaning:'ngủ',      emoji:'😴'},
    ]},
  { id:'Z',   label:'Z',   ipa:'z',  type:'consonant', group:'Fricatives',
    color:'bg-slate-600',   grad:'from-slate-600 to-slate-800',    hard:false,
    tip:'Giống S nhưng RUNG HỌng. Hay xuất hiện ở cuối từ số nhiều (-s) và động từ',
    words:[
      {word:'lazy',  meaning:'lười biếng',emoji:'😴'},
      {word:'zebra', meaning:'ngựa vằn', emoji:'🦓'},
      {word:'music', meaning:'âm nhạc',  emoji:'🎵'},
      {word:'nose',  meaning:'cái mũi',  emoji:'👃'},
    ]},
  { id:'SH',  label:'SH',  ipa:'ʃ',  type:'consonant', group:'Fricatives',
    color:'bg-fuchsia-700', grad:'from-fuchsia-700 to-fuchsia-900',hard:false,
    tip:'Chu môi nhẹ ra phía trước, thổi khí. Không rung họng. Như "ssh" khi bảo im lặng',
    words:[
      {word:'shiny', meaning:'sáng bóng',emoji:'✨'},
      {word:'shoes', meaning:'đôi giày', emoji:'👟'},
      {word:'she',   meaning:'cô ấy',   emoji:'👩'},
      {word:'wish',  meaning:'mong muốn',emoji:'⭐'},
    ]},
  { id:'ZH',  label:'ZH',  ipa:'ʒ',  type:'consonant', group:'Fricatives',
    color:'bg-red-800',     grad:'from-red-800 to-red-950',        hard:true,
    tip:'Giống SH nhưng RUNG HỌng. Ít gặp — chỉ trong "measure, treasure, vision"',
    words:[
      {word:'measure',  meaning:'đo lường',emoji:'📏'},
      {word:'treasure', meaning:'kho báu', emoji:'💎'},
      {word:'usual',    meaning:'thông thường',emoji:'📋'},
      {word:'vision',   meaning:'tầm nhìn',emoji:'👁️'},
    ]},
  { id:'H',   label:'H',   ipa:'h',  type:'consonant', group:'Fricatives',
    color:'bg-rose-600',    grad:'from-rose-600 to-rose-800',      hard:false,
    tip:'Thổi khí nhẹ từ họng, như hơi thở nhẹ. Không rung họng. Đơn giản nhất!',
    words:[
      {word:'happy', meaning:'vui vẻ',    emoji:'😊'},
      {word:'hippo', meaning:'hà mã',     emoji:'🦛'},
      {word:'home',  meaning:'nhà',       emoji:'🏠'},
      {word:'hand',  meaning:'bàn tay',   emoji:'✋'},
    ]},

  // ════════════════════════════════════════════════════════════
  // CONSONANTS — Approximants · 4 sounds
  // ════════════════════════════════════════════════════════════
  { id:'R',   label:'R',   ipa:'r',  type:'consonant', group:'Approximants',
    color:'bg-teal-600',    grad:'from-teal-600 to-teal-800',      hard:true,
    tip:'KHÔNG CHẠM LƯỠI VÀO ĐÂU — cuộn lưỡi ra sau giữa không khí, môi hơi thu tròn. Khác /l/ hoàn toàn!',
    words:[
      {word:'prickly',meaning:'gai góc',  emoji:'🌵'},
      {word:'branch', meaning:'cành cây', emoji:'🌿'},
      {word:'road',   meaning:'con đường',emoji:'🛣️'},
      {word:'really', meaning:'thực sự',  emoji:'💯'},
    ]},
  { id:'Y',   label:'Y',   ipa:'j',  type:'consonant', group:'Approximants',
    color:'bg-pink-500',    grad:'from-pink-500 to-pink-700',      hard:false,
    tip:'Lưỡi cao phía trước, miệng hé — giống "i" tiếng Việt nhưng chuyển sang nguyên âm ngay',
    words:[
      {word:'yummy',  meaning:'ngon',     emoji:'😋'},
      {word:'yogurt', meaning:'sữa chua', emoji:'🥛'},
      {word:'year',   meaning:'năm',      emoji:'📅'},
      {word:'you',    meaning:'bạn',      emoji:'👤'},
    ]},
  { id:'W',   label:'W',   ipa:'w',  type:'consonant', group:'Approximants',
    color:'bg-sky-600',     grad:'from-sky-600 to-sky-800',        hard:true,
    tip:'Chu môi tròn như chuẩn bị nói "oa", KHÔNG dùng răng. Khác /v/ hoàn toàn!',
    words:[
      {word:'wonderful',meaning:'tuyệt vời',emoji:'🌟'},
      {word:'whale',    meaning:'cá voi',  emoji:'🐋'},
      {word:'water',    meaning:'nước',    emoji:'💧'},
      {word:'world',    meaning:'thế giới',emoji:'🌍'},
    ]},
  { id:'L',   label:'L',   ipa:'l',  type:'consonant', group:'Approximants',
    color:'bg-purple-600',  grad:'from-purple-600 to-purple-800',  hard:false,
    tip:'ĐẦU LƯỠI CHẠM sau răng cửa trên. Khác /r/: lưỡi chạm một điểm cố định',
    words:[
      {word:'lemon',    meaning:'chanh',     emoji:'🍋'},
      {word:'lollipop', meaning:'kẹo mút',   emoji:'🍭'},
      {word:'light',    meaning:'ánh sáng',  emoji:'💡'},
      {word:'world',    meaning:'thế giới',  emoji:'🌍'},
    ]},

  // ════════════════════════════════════════════════════════════
  // CONSONANTS — Affricates · 2 sounds
  // ════════════════════════════════════════════════════════════
  { id:'CH',  label:'CH',  ipa:'tʃ', type:'consonant', group:'Affricates',
    color:'bg-amber-600',   grad:'from-amber-600 to-amber-800',    hard:false,
    tip:'Kết hợp /t/ + /ʃ/ liền nhau. Lưỡi chạm vòm miệng rồi bật ra với luồng khí',
    words:[
      {word:'cheddar', meaning:'phô mai',  emoji:'🧀'},
      {word:'cheese',  meaning:'phô mai',  emoji:'🧀'},
      {word:'church',  meaning:'nhà thờ',  emoji:'⛪'},
      {word:'teacher', meaning:'giáo viên',emoji:'👩‍🏫'},
    ]},
  { id:'J',   label:'J',   ipa:'dʒ', type:'consonant', group:'Affricates',
    color:'bg-orange-500',  grad:'from-orange-500 to-orange-700',  hard:false,
    tip:'Giống CH nhưng RUNG HỌng. Kết hợp /d/ + /ʒ/. Như "judge, just, magic"',
    words:[
      {word:'gentle', meaning:'nhẹ nhàng',emoji:'🕊️'},
      {word:'giant',  meaning:'khổng lồ', emoji:'🦕'},
      {word:'just',   meaning:'vừa, chỉ', emoji:'🎯'},
      {word:'enjoy',  meaning:'tận hưởng',emoji:'😄'},
    ]},

  // ════════════════════════════════════════════════════════════
  // CONSONANTS — Tap · 1 sound
  // ════════════════════════════════════════════════════════════
  { id:'DD',  label:'DD',  ipa:'ɾ',  type:'consonant', group:'Tap',
    color:'bg-violet-700',  grad:'from-violet-700 to-violet-900',  hard:true,
    tip:'Flap T — âm đặc trưng giọng Mỹ: /t/ và /d/ giữa hai nguyên âm phát âm như "d" nhanh. "butter" = "budder"',
    words:[
      {word:'muddy',  meaning:'bùn lầy',  emoji:'🌧️'},
      {word:'city',   meaning:'thành phố',emoji:'🏙️'},
      {word:'water',  meaning:'nước',     emoji:'💧'},
      {word:'better', meaning:'tốt hơn',  emoji:'⬆️'},
    ]},
]

// Grouped for the Sound Library UI
export const VOWEL_GROUPS = [
  { label: 'Single Vowels', key: 'Single Vowels', count: 14 },
  { label: 'Diphthongs',    key: 'Diphthongs',    count: 9  },
]
export const CONSONANT_GROUPS = [
  { label: 'Plosives',      key: 'Plosives',      count: 6 },
  { label: 'Nasals',        key: 'Nasals',         count: 3 },
  { label: 'Fricatives',    key: 'Fricatives',     count: 9 },
  { label: 'Approximants',  key: 'Approximants',   count: 4 },
  { label: 'Affricates',    key: 'Affricates',     count: 2 },
  { label: 'Tap',           key: 'Tap',            count: 1 },
]

// ─── SPANISH PHONEME INFO ──────────────────────────────────────────────────
// phoneme IPA → { tip (Vietnamese), hard }
export const SPANISH_PHONEME_INFO = {
  'a':  { tip: 'Âm "a" thuần — mở miệng rộng, lưỡi thấp. Không thay đổi chất âm như tiếng Anh', hard: false },
  'e':  { tip: 'Âm "ê" thuần — lưỡi giữa-cao, môi hơi kéo. Không trượt lên /i/ như tiếng Anh', hard: false },
  'i':  { tip: 'Âm "i" thuần — lưỡi cao phía trước, môi kéo sang ngang', hard: false },
  'o':  { tip: 'Âm "ô" thuần — môi tròn vừa, lưỡi giữa-sau. Không trượt lên /u/ như tiếng Anh', hard: false },
  'u':  { tip: 'Âm "u" thuần — môi tròn căng, lưỡi sau cao', hard: false },
  'ai': { tip: 'Diphthong /ai/ — bắt đầu "a" rồi trượt nhanh sang /i/. Như "ai/ay" trong "aire, hay"', hard: false },
  'ei': { tip: 'Diphthong /ei/ — bắt đầu /e/ rồi trượt sang /i/. Như "ei/ey" trong "reina, ley"', hard: false },
  'oi': { tip: 'Diphthong /oi/ — bắt đầu /o/ rồi trượt sang /i/. Như "oi/oy" trong "boina, soy"', hard: false },
  'ui': { tip: 'Diphthong /ui/ — bắt đầu /u/ rồi trượt sang /i/. Như "ruido, muy"', hard: false },
  'ja': { tip: 'Bán nguyên âm /j/ + /a/ — như "ia/ya" trong "viaje". Lưỡi cao rồi mở nhanh xuống /a/', hard: false },
  'je': { tip: 'Bán nguyên âm /j/ + /e/ — như "ie" trong "tierra". Âm đầu lướt nhanh như "y"', hard: false },
  'jo': { tip: 'Bán nguyên âm /j/ + /o/ — như "io/yo" trong "violeta".', hard: false },
  'ju': { tip: 'Bán nguyên âm /j/ + /u/ — như "iu/yu" trong "ciudad".', hard: false },
  'wa': { tip: 'Bán nguyên âm /w/ + /a/ — như "ua" trong "cuadro". Chu môi nhanh rồi mở sang /a/', hard: false },
  'we': { tip: 'Bán nguyên âm /w/ + /e/ — như "ue" trong "puerta".', hard: false },
  'wo': { tip: 'Bán nguyên âm /w/ + /o/ — như "uo" trong "antiguo".', hard: false },
  'ɾ':  { tip: 'Chạm nhẹ đầu lưỡi vào vòm một lần — như "đ" nhanh. Dùng khi "r" đứng giữa hai nguyên âm', hard: false },
  'r':  { tip: 'Rung đầu lưỡi nhiều lần liên tiếp (trill) — khó nhất tiếng Tây Ban Nha! Đặt lưỡi gần vòm, thổi hơi qua', hard: true },
  'x':  { tip: 'Thổi khí mạnh qua cổ họng phía sau — như hắng giọng. Âm này không có trong tiếng Việt!', hard: true },
  'ɲ':  { tip: 'Giống "nh" trong tiếng Việt — lưỡi chạm vòm giữa, âm mũi. Dễ với người Việt!', hard: false },
  'j':  { tip: 'Âm "y" (bán nguyên âm) — lưỡi cao phía trước, không chạm vòm. Như "y" trong "yes"', hard: false },
  'β':  { tip: 'Môi trên và môi dưới gần nhau, thổi hơi qua khe giữa — nhẹ hơn /b/ tiếng Việt', hard: true },
  'ð':  { tip: 'Đầu lưỡi chạm rất nhẹ gần răng trên, rung họng. Đây là biến thể mềm của /d/ giữa nguyên âm', hard: true },
  'ɣ':  { tip: 'Mặt sau lưỡi gần vòm mềm, thổi hơi có rung họng. Biến thể mềm của /g/ giữa nguyên âm', hard: true },
  'tʃ': { tip: 'Âm "ch" — lưỡi chạm vòm rồi mở ra thổi. Như "ch" trong tiếng Anh "church"', hard: false },
  'n':  { tip: 'Đầu lưỡi chạm sau răng cửa trên, âm mũi — như "n" tiếng Việt', hard: false },
  'm':  { tip: 'Khép môi, rung âm mũi — như "m" tiếng Việt', hard: false },
  'l':  { tip: 'Đầu lưỡi chạm sau răng trên — như "l" tiếng Việt', hard: false },
  'p':  { tip: 'Bật môi — ít bật hơi hơn tiếng Anh, gần giống "p" tiếng Việt', hard: false },
  'b':  { tip: 'Bật môi, rung họng — như "b" tiếng Việt', hard: false },
  't':  { tip: 'Lưỡi chạm sau răng (dental) — như "t" tiếng Việt, không bật hơi', hard: false },
  'd':  { tip: 'Lưỡi chạm sau răng, rung họng — như "đ" tiếng Việt', hard: false },
  'k':  { tip: 'Lưỡi chạm vòm mềm, bật ra — như "c/k" tiếng Việt', hard: false },
  'g':  { tip: 'Lưỡi chạm vòm mềm, rung họng — như "g" tiếng Việt', hard: false },
  'f':  { tip: 'Răng trên đặt lên môi dưới, thổi khí — như "ph" tiếng Việt', hard: false },
  's':  { tip: 'Đầu lưỡi gần răng, thổi khí — như "s/x" tiếng Việt', hard: false },
  'θ':  { tip: 'Âm "th" Tây Ban Nha (Castilian) — đặt đầu lưỡi giữa hai răng, thổi khí nhẹ. Như "th" trong "think"', hard: true },
  'ʎ':  { tip: 'Lưỡi phẳng chạm vòm giữa, âm bên — như "l" nhưng lưỡi rộng hơn', hard: true },
  'gw': { tip: 'Âm "gu" — /g/ + bán nguyên âm /w/', hard: false },
  'je': { tip: 'Diphthong ie — /j/ trượt thành /e/, miệng mở dần', hard: false },
  'h':  { tip: 'Câm trong tiếng Tây Ban Nha — không phát âm', hard: false },
  'w':  { tip: 'Bán nguyên âm /w/ — chu môi nhanh như "u" ngắn rồi vào nguyên âm tiếp theo', hard: false },
  'ks': { tip: 'Cụm /k/ + /s/ — như "x" trong nhiều từ mượn: taxi, examen', hard: false },
  '∅':  { tip: 'Chữ câm — nhìn thấy trong chính tả nhưng không phát âm', hard: false },
}

// ─── SPANISH SOUNDS (mở rộng) ─────────────────────────────────────────────
export const SPANISH_SOUNDS = [
  // ════ NGUYÊN ÂM ═══════════════════════════════════════════
  { id:'ES_A', label:'a', ipa:'a', type:'vowel', group:'Nguyên Âm',
    color:'bg-red-700', grad:'from-red-700 to-red-900', hard:false,
    tip:'Âm "a" thuần — mở miệng rộng, lưỡi thấp phẳng. Ngắn và rõ, không thay đổi chất âm',
    words:[
      {word:'casa',  meaning:'ngôi nhà', emoji:'🏠', phonemes:[['c','k'],['a','a'],['s','s'],['a','a']]},
      {word:'mano',  meaning:'bàn tay',  emoji:'✋', phonemes:[['m','m'],['a','a'],['n','n'],['o','o']]},
      {word:'sala',  meaning:'phòng khách',emoji:'🛋️', phonemes:[['s','s'],['a','a'],['l','l'],['a','a']]},
    ]},
  { id:'ES_E', label:'e', ipa:'e', type:'vowel', group:'Nguyên Âm',
    color:'bg-pink-600', grad:'from-pink-600 to-pink-800', hard:false,
    tip:'Âm "ê" thuần — lưỡi giữa-cao, không trượt. Khác tiếng Anh: không biến thành /eɪ/',
    words:[
      {word:'mesa',  meaning:'cái bàn',  emoji:'🪑', phonemes:[['m','m'],['e','e'],['s','s'],['a','a']]},
      {word:'verde', meaning:'màu xanh lá',emoji:'🟢', phonemes:[['v','β'],['e','e'],['r','ɾ'],['d','d'],['e','e']]},
      {word:'tres',  meaning:'số ba',    emoji:'3️⃣', phonemes:[['tr','tr'],['e','e'],['s','s']]},
    ]},
  { id:'ES_I', label:'i', ipa:'i', type:'vowel', group:'Nguyên Âm',
    color:'bg-purple-700', grad:'from-purple-700 to-purple-900', hard:false,
    tip:'Âm "i" thuần — lưỡi cao phía trước. Sạch hơn /iː/ tiếng Anh: ngắn và nhất quán',
    words:[
      {word:'libro',  meaning:'cuốn sách',emoji:'📖', phonemes:[['l','l'],['i','i'],['br','βr'],['o','o']]},
      {word:'piso',   meaning:'tầng/sàn', emoji:'🏢', phonemes:[['p','p'],['i','i'],['s','s'],['o','o']]},
      {word:'rico',   meaning:'ngon/giàu',emoji:'😋', phonemes:[['r','ɾ'],['i','i'],['c','k'],['o','o']]},
    ]},
  { id:'ES_O', label:'o', ipa:'o', type:'vowel', group:'Nguyên Âm',
    color:'bg-teal-600', grad:'from-teal-600 to-teal-800', hard:false,
    tip:'Âm "ô" thuần — môi tròn vừa, lưỡi giữa-sau. Không trượt lên /u/ như "go" tiếng Anh',
    words:[
      {word:'boca',  meaning:'cái miệng',emoji:'👄', phonemes:[['b','b'],['o','o'],['c','k'],['a','a']]},
      {word:'moto',  meaning:'xe máy',   emoji:'🏍️', phonemes:[['m','m'],['o','o'],['t','t'],['o','o']]},
      {word:'sol',   meaning:'mặt trời', emoji:'☀️', phonemes:[['s','s'],['o','o'],['l','l']]},
    ]},
  { id:'ES_U', label:'u', ipa:'u', type:'vowel', group:'Nguyên Âm',
    color:'bg-cyan-600', grad:'from-cyan-600 to-cyan-800', hard:false,
    tip:'Âm "u" thuần — môi tròn căng, lưỡi sau. Sạch và ngắn hơn /uː/ tiếng Anh',
    words:[
      {word:'luna',  meaning:'mặt trăng',emoji:'🌙', phonemes:[['l','l'],['u','u'],['n','n'],['a','a']]},
      {word:'mucho', meaning:'rất nhiều',emoji:'💯', phonemes:[['m','m'],['u','u'],['ch','tʃ'],['o','o']]},
      {word:'gusto', meaning:'niềm vui', emoji:'😊', phonemes:[['g','g'],['u','u'],['s','s'],['t','t'],['o','o']]},
    ]},
  // ════ NGUYÊN ÂM ĐÔI PHỔ BIẾN ════════════════════════════════
  { id:'ES_AI', label:'ai/ay', ipa:'ai', type:'vowel', group:'Nguyên Âm Đôi',
    color:'bg-amber-600', grad:'from-amber-600 to-amber-800', hard:false,
    tip:'Nhóm "ai/ay" — bắt đầu /a/ rồi trượt nhanh sang /i/',
    words:[
      {word:'aire', meaning:'không khí', emoji:'🌬️', phonemes:[['ai','ai'],['r','ɾ'],['e','e']]},
      {word:'hay',  meaning:'có',        emoji:'✅', phonemes:[['ay','ai']]},
    ]},
  { id:'ES_EI', label:'ei/ey', ipa:'ei', type:'vowel', group:'Nguyên Âm Đôi',
    color:'bg-orange-600', grad:'from-orange-600 to-orange-800', hard:false,
    tip:'Nhóm "ei/ey" — /e/ trượt sang /i/',
    words:[
      {word:'reina', meaning:'nữ hoàng', emoji:'👑', phonemes:[['r','r'],['ei','ei'],['n','n'],['a','a']]},
      {word:'ley',   meaning:'luật',     emoji:'⚖️', phonemes:[['l','l'],['ey','ei']]},
    ]},
  { id:'ES_OI', label:'oi/oy', ipa:'oi', type:'vowel', group:'Nguyên Âm Đôi',
    color:'bg-lime-600', grad:'from-lime-600 to-lime-800', hard:false,
    tip:'Nhóm "oi/oy" — /o/ trượt sang /i/',
    words:[
      {word:'boina', meaning:'mũ nồi', emoji:'🧢', phonemes:[['b','b'],['oi','oi'],['n','n'],['a','a']]},
      {word:'soy',   meaning:'tôi là', emoji:'🙋', phonemes:[['s','s'],['oy','oi']]},
    ]},
  { id:'ES_UI', label:'ui/uy', ipa:'ui', type:'vowel', group:'Nguyên Âm Đôi',
    color:'bg-emerald-600', grad:'from-emerald-600 to-emerald-800', hard:false,
    tip:'Nhóm "ui/uy" — /u/ trượt sang /i/',
    words:[
      {word:'ruido', meaning:'tiếng ồn', emoji:'🔊', phonemes:[['r','r'],['ui','ui'],['d','d'],['o','o']]},
      {word:'muy',   meaning:'rất',      emoji:'💯', phonemes:[['m','m'],['uy','ui']]},
    ]},
  { id:'ES_IA', label:'ia', ipa:'ja', type:'vowel', group:'Nguyên Âm Đôi',
    color:'bg-teal-600', grad:'from-teal-600 to-teal-800', hard:false,
    tip:'"ia" thường tạo bán nguyên âm /j/ rồi sang /a/',
    words:[
      {word:'viaje', meaning:'chuyến đi', emoji:'✈️', phonemes:[['v','β'],['ia','ja'],['j','x'],['e','e']]},
      {word:'diario', meaning:'hằng ngày', emoji:'🗓️', phonemes:[['d','d'],['ia','ja'],['r','ɾ'],['io','jo']]},
    ]},
  { id:'ES_IE', label:'ie', ipa:'je', type:'vowel', group:'Nguyên Âm Đôi',
    color:'bg-cyan-600', grad:'from-cyan-600 to-cyan-800', hard:false,
    tip:'"ie" — /j/ trượt sang /e/',
    words:[
      {word:'tierra', meaning:'đất đai', emoji:'🌍', phonemes:[['t','t'],['ie','je'],['rr','r'],['a','a']]},
      {word:'bien',   meaning:'tốt',     emoji:'👍', phonemes:[['b','b'],['ie','je'],['n','n']]},
    ]},
  { id:'ES_IO', label:'io', ipa:'jo', type:'vowel', group:'Nguyên Âm Đôi',
    color:'bg-sky-600', grad:'from-sky-600 to-sky-800', hard:false,
    tip:'"io" — /j/ trượt sang /o/',
    words:[
      {word:'violeta', meaning:'màu tím', emoji:'🟣', phonemes:[['v','β'],['io','jo'],['l','l'],['e','e'],['t','t'],['a','a']]},
      {word:'avión',   meaning:'máy bay', emoji:'✈️', phonemes:[['a','a'],['v','β'],['io','jo'],['n','n']]},
    ]},
  { id:'ES_IU', label:'iu', ipa:'ju', type:'vowel', group:'Nguyên Âm Đôi',
    color:'bg-blue-600', grad:'from-blue-600 to-blue-800', hard:false,
    tip:'"iu" — /j/ trượt sang /u/',
    words:[
      {word:'ciudad', meaning:'thành phố', emoji:'🏙️', phonemes:[['c','s'],['iu','ju'],['d','ð'],['a','a'],['d','d']]},
      {word:'viuda',  meaning:'góa phụ',   emoji:'🖤', phonemes:[['v','β'],['iu','ju'],['d','d'],['a','a']]},
    ]},
  { id:'ES_UA', label:'ua', ipa:'wa', type:'vowel', group:'Nguyên Âm Đôi',
    color:'bg-indigo-600', grad:'from-indigo-600 to-indigo-800', hard:false,
    tip:'"ua" — /w/ trượt sang /a/',
    words:[
      {word:'cuadro', meaning:'bức tranh', emoji:'🖼️', phonemes:[['c','k'],['ua','wa'],['dr','dr'],['o','o']]},
      {word:'guapo',  meaning:'đẹp trai',  emoji:'😎', phonemes:[['g','g'],['ua','wa'],['p','p'],['o','o']]},
    ]},
  { id:'ES_UE', label:'ue', ipa:'we', type:'vowel', group:'Nguyên Âm Đôi',
    color:'bg-violet-600', grad:'from-violet-600 to-violet-800', hard:false,
    tip:'"ue" — /w/ trượt sang /e/',
    words:[
      {word:'puerta', meaning:'cánh cửa', emoji:'🚪', phonemes:[['p','p'],['ue','we'],['r','ɾ'],['t','t'],['a','a']]},
      {word:'bueno',  meaning:'tốt',      emoji:'👍', phonemes:[['b','b'],['ue','we'],['n','n'],['o','o']]},
    ]},
  { id:'ES_UO', label:'uo', ipa:'wo', type:'vowel', group:'Nguyên Âm Đôi',
    color:'bg-fuchsia-600', grad:'from-fuchsia-600 to-fuchsia-800', hard:false,
    tip:'"uo" — /w/ trượt sang /o/, ít gặp hơn nhưng vẫn phổ biến trong vài từ',
    words:[
      {word:'antiguo', meaning:'cổ xưa', emoji:'🏺', phonemes:[['a','a'],['n','n'],['t','t'],['i','i'],['g','ɣ'],['uo','wo']]},
      {word:'cuota',   meaning:'hạn mức', emoji:'💳', phonemes:[['c','k'],['uo','wo'],['t','t'],['a','a']]},
    ]},
  // ════ PHỤ ÂM CƠ BẢN ════════════════════════════════════════
  { id:'ES_BV', label:'b / v', ipa:'b~β', type:'consonant', group:'Phụ Âm Cơ Bản',
    color:'bg-rose-700', grad:'from-rose-700 to-rose-900', hard:true,
    tip:'Trong tiếng Tây Ban Nha, B và V gần như đọc giống nhau. Đầu từ thường gần /b/, giữa nguyên âm thường mềm hơn thành /β/',
    words:[
      {word:'barco', meaning:'con tàu', emoji:'⛵', phonemes:[['b','b'],['a','a'],['r','r'],['c','k'],['o','o']]},
      {word:'vino',  meaning:'rượu vang', emoji:'🍷', phonemes:[['v','β'],['i','i'],['n','n'],['o','o']]},
    ]},
  { id:'ES_C', label:'c', ipa:'k / s', type:'consonant', group:'Phụ Âm Cơ Bản',
    color:'bg-red-600', grad:'from-red-600 to-red-800', hard:false,
    tip:'C đọc là /k/ trước a/o/u, và thường là /s/ trước e/i trong cách dạy cơ bản',
    words:[
      {word:'casa', meaning:'ngôi nhà', emoji:'🏠', phonemes:[['c','k'],['a','a'],['s','s'],['a','a']]},
      {word:'cine', meaning:'rạp phim', emoji:'🎬', phonemes:[['c','s'],['i','i'],['n','n'],['e','e']]},
    ]},
  { id:'ES_CH', label:'ch', ipa:'tʃ', type:'consonant', group:'Phụ Âm Cơ Bản',
    color:'bg-orange-700', grad:'from-orange-700 to-orange-900', hard:false,
    tip:'Âm "ch" — lưỡi chạm vòm rồi mở ra thổi hơi. Như "ch" tiếng Anh nhưng gọn hơn',
    words:[
      {word:'chico', meaning:'cậu bé', emoji:'👦', phonemes:[['ch','tʃ'],['i','i'],['c','k'],['o','o']]},
      {word:'leche', meaning:'sữa',     emoji:'🥛', phonemes:[['l','l'],['e','e'],['ch','tʃ'],['e','e']]},
    ]},
  { id:'ES_D', label:'d', ipa:'d / ð', type:'consonant', group:'Phụ Âm Cơ Bản',
    color:'bg-amber-700', grad:'from-amber-700 to-amber-900', hard:true,
    tip:'D đầu từ thường gần /d/, giữa nguyên âm thường mềm thành /ð/',
    words:[
      {word:'dedo', meaning:'ngón tay', emoji:'☝️', phonemes:[['d','d'],['e','e'],['d','ð'],['o','o']]},
      {word:'nada', meaning:'không gì', emoji:'🚫', phonemes:[['n','n'],['a','a'],['d','ð'],['a','a']]},
    ]},
  { id:'ES_F', label:'f', ipa:'f', type:'consonant', group:'Phụ Âm Cơ Bản',
    color:'bg-yellow-700', grad:'from-yellow-700 to-yellow-900', hard:false,
    tip:'F ổn định như /f/ tiếng Việt hoặc tiếng Anh',
    words:[
      {word:'foto', meaning:'bức ảnh', emoji:'📷', phonemes:[['f','f'],['o','o'],['t','t'],['o','o']]},
      {word:'fresa', meaning:'dâu tây', emoji:'🍓', phonemes:[['f','f'],['r','r'],['e','e'],['s','s'],['a','a']]},
    ]},
  { id:'ES_G', label:'g', ipa:'g / x', type:'consonant', group:'Phụ Âm Cơ Bản',
    color:'bg-lime-700', grad:'from-lime-700 to-lime-900', hard:true,
    tip:'G đọc là /g/ trước a/o/u, và thành /x/ trước e/i nếu không có u câm',
    words:[
      {word:'gato', meaning:'con mèo', emoji:'🐱', phonemes:[['g','g'],['a','a'],['t','t'],['o','o']]},
      {word:'gente', meaning:'mọi người', emoji:'👥', phonemes:[['g','x'],['e','e'],['n','n'],['t','t'],['e','e']]},
    ]},
  { id:'ES_H', label:'h', ipa:'∅', type:'consonant', group:'Phụ Âm Cơ Bản',
    color:'bg-teal-700', grad:'from-teal-700 to-teal-900', hard:false,
    tip:'H là chữ câm trong tiếng Tây Ban Nha chuẩn — nhìn thấy nhưng không phát âm',
    words:[
      {word:'hola', meaning:'xin chào', emoji:'👋', phonemes:[['o','o'],['l','l'],['a','a']]},
      {word:'huevo', meaning:'trứng',    emoji:'🥚', phonemes:[['ue','we'],['v','β'],['o','o']]},
    ]},
  { id:'ES_J', label:'j', ipa:'x', type:'consonant', group:'Phụ Âm Cơ Bản',
    color:'bg-cyan-700', grad:'from-cyan-700 to-cyan-900', hard:true,
    tip:'J gần như luôn là /x/ — thổi khí mạnh qua cổ họng phía sau',
    words:[
      {word:'jamón', meaning:'giăm bông', emoji:'🍖', phonemes:[['j','x'],['a','a'],['m','m'],['o','o'],['n','n']]},
      {word:'ojo',   meaning:'con mắt',   emoji:'👁️', phonemes:[['o','o'],['j','x'],['o','o']]},
    ]},
  { id:'ES_K', label:'k', ipa:'k', type:'consonant', group:'Phụ Âm Cơ Bản',
    color:'bg-sky-700', grad:'from-sky-700 to-sky-900', hard:false,
    tip:'K luôn đọc là /k/, ít gặp hơn vì đa số từ gốc Tây Ban Nha dùng c/qu',
    words:[
      {word:'kilo',  meaning:'ki-lô', emoji:'⚖️', phonemes:[['k','k'],['i','i'],['l','l'],['o','o']]},
      {word:'koala', meaning:'gấu koala', emoji:'🐨', phonemes:[['k','k'],['o','o'],['a','a'],['l','l'],['a','a']]},
    ]},
  { id:'ES_L', label:'l', ipa:'l', type:'consonant', group:'Phụ Âm Cơ Bản',
    color:'bg-indigo-700', grad:'from-indigo-700 to-indigo-900', hard:false,
    tip:'L khá giống tiếng Việt, đầu lưỡi chạm sau răng trên',
    words:[
      {word:'luna', meaning:'mặt trăng', emoji:'🌙', phonemes:[['l','l'],['u','u'],['n','n'],['a','a']]},
      {word:'sol',  meaning:'mặt trời',  emoji:'☀️', phonemes:[['s','s'],['o','o'],['l','l']]},
    ]},
  { id:'ES_LL', label:'ll', ipa:'j', type:'consonant', group:'Phụ Âm Cơ Bản',
    color:'bg-violet-700', grad:'from-violet-700 to-violet-900', hard:false,
    tip:'Trong đa số cách nói hiện đại, LL phát âm gần như Y = /j/',
    words:[
      {word:'llama', meaning:'ngọn lửa', emoji:'🔥', phonemes:[['ll','j'],['a','a'],['m','m'],['a','a']]},
      {word:'llave', meaning:'chìa khóa', emoji:'🔑', phonemes:[['ll','j'],['a','a'],['v','β'],['e','e']]},
    ]},
  { id:'ES_M', label:'m', ipa:'m', type:'consonant', group:'Phụ Âm Cơ Bản',
    color:'bg-fuchsia-700', grad:'from-fuchsia-700 to-fuchsia-900', hard:false,
    tip:'M giống tiếng Việt — khép môi và rung mũi',
    words:[
      {word:'mano', meaning:'bàn tay', emoji:'✋', phonemes:[['m','m'],['a','a'],['n','n'],['o','o']]},
      {word:'mamá', meaning:'mẹ', emoji:'👩', phonemes:[['m','m'],['a','a'],['m','m'],['a','a']]},
    ]},
  { id:'ES_N', label:'n', ipa:'n', type:'consonant', group:'Phụ Âm Cơ Bản',
    color:'bg-blue-700', grad:'from-blue-700 to-blue-900', hard:false,
    tip:'N khá giống tiếng Việt — đầu lưỡi chạm sau răng trên',
    words:[
      {word:'nada', meaning:'không gì', emoji:'🚫', phonemes:[['n','n'],['a','a'],['d','ð'],['a','a']]},
      {word:'pan',  meaning:'bánh mì',  emoji:'🍞', phonemes:[['p','p'],['a','a'],['n','n']]},
    ]},
  { id:'ES_Ñ', label:'ñ', ipa:'ɲ', type:'consonant', group:'Phụ Âm Cơ Bản',
    color:'bg-emerald-700', grad:'from-emerald-700 to-emerald-900', hard:false,
    tip:'Ñ = /ɲ/ — như "nh" trong tiếng Việt',
    words:[
      {word:'niño', meaning:'đứa trẻ', emoji:'👦', phonemes:[['n','n'],['i','i'],['ñ','ɲ'],['o','o']]},
      {word:'baño', meaning:'phòng tắm', emoji:'🚿', phonemes:[['b','b'],['a','a'],['ñ','ɲ'],['o','o']]},
    ]},
  { id:'ES_P', label:'p', ipa:'p', type:'consonant', group:'Phụ Âm Cơ Bản',
    color:'bg-green-700', grad:'from-green-700 to-green-900', hard:false,
    tip:'P ngắn và ít bật hơi hơn tiếng Anh',
    words:[
      {word:'papa', meaning:'khoai tây', emoji:'🥔', phonemes:[['p','p'],['a','a'],['p','p'],['a','a']]},
      {word:'pan',  meaning:'bánh mì', emoji:'🍞', phonemes:[['p','p'],['a','a'],['n','n']]},
    ]},
  { id:'ES_Q', label:'q', ipa:'k', type:'consonant', group:'Phụ Âm Cơ Bản',
    color:'bg-amber-600', grad:'from-amber-600 to-amber-800', hard:false,
    tip:'Q hầu như luôn đi với u câm: que/qui vẫn đọc là /ke/ /ki/',
    words:[
      {word:'queso', meaning:'pho mát', emoji:'🧀', phonemes:[['qu','k'],['e','e'],['s','s'],['o','o']]},
      {word:'quince', meaning:'mười lăm', emoji:'1️⃣5️⃣', phonemes:[['qu','k'],['i','i'],['n','n'],['c','s'],['e','e']]},
    ]},
  { id:'ES_R1', label:'r', ipa:'ɾ', type:'consonant', group:'Phụ Âm Cơ Bản',
    color:'bg-amber-600', grad:'from-amber-600 to-amber-800', hard:false,
    tip:'Tap r — chạm nhẹ đầu lưỡi vào vòm một lần. Dùng khi "r" đứng giữa nguyên âm, ngắn và nhẹ',
    words:[
      {word:'cara',  meaning:'khuôn mặt',emoji:'😊', phonemes:[['c','k'],['a','a'],['r','ɾ'],['a','a']]},
      {word:'pero',  meaning:'nhưng',    emoji:'↔️', phonemes:[['p','p'],['e','e'],['r','ɾ'],['o','o']]},
    ]},
  { id:'ES_RR', label:'rr', ipa:'r', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-orange-700', grad:'from-orange-700 to-orange-900', hard:true,
    tip:'Trill r — rung đầu lưỡi nhiều lần liên tiếp. Âm khó nhất! Tập bằng cách nói "ddddd" nhanh với lưỡi gần vòm',
    words:[
      {word:'perro',  meaning:'con chó',  emoji:'🐕', phonemes:[['p','p'],['e','e'],['rr','r'],['o','o']]},
      {word:'tierra', meaning:'đất đai',  emoji:'🌍', phonemes:[['t','t'],['ie','je'],['rr','r'],['a','a']]},
    ]},
  { id:'ES_S', label:'s', ipa:'s', type:'consonant', group:'Phụ Âm Cơ Bản',
    color:'bg-red-700', grad:'from-red-700 to-red-900', hard:false,
    tip:'S thường ổn định là /s/',
    words:[
      {word:'sopa', meaning:'súp', emoji:'🥣', phonemes:[['s','s'],['o','o'],['p','p'],['a','a']]},
      {word:'casa', meaning:'ngôi nhà', emoji:'🏠', phonemes:[['c','k'],['a','a'],['s','s'],['a','a']]},
    ]},
  { id:'ES_T', label:'t', ipa:'t', type:'consonant', group:'Phụ Âm Cơ Bản',
    color:'bg-pink-700', grad:'from-pink-700 to-pink-900', hard:false,
    tip:'T là âm dental, đầu lưỡi chạm răng trên. Không bật hơi mạnh như tiếng Anh',
    words:[
      {word:'taco', meaning:'bánh taco', emoji:'🌮', phonemes:[['t','t'],['a','a'],['c','k'],['o','o']]},
      {word:'taza', meaning:'cái cốc', emoji:'☕', phonemes:[['t','t'],['a','a'],['z','θ'],['a','a']]},
    ]},
  { id:'ES_W', label:'w', ipa:'w', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-purple-700', grad:'from-purple-700 to-purple-900', hard:false,
    tip:'W chủ yếu xuất hiện trong từ mượn. Thường đọc gần /w/',
    words:[
      {word:'wifi', meaning:'wifi', emoji:'📶', phonemes:[['w','w'],['i','i'],['f','f'],['i','i']]},
      {word:'web',  meaning:'trang web', emoji:'🌐', phonemes:[['w','w'],['e','e'],['b','β']]},
    ]},
  { id:'ES_X', label:'x', ipa:'ks / s / x', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-teal-700', grad:'from-teal-700 to-teal-900', hard:true,
    tip:'X có nhiều cách đọc tùy từ: thường là /ks/, đôi khi /s/ hoặc /x/',
    words:[
      {word:'taxi', meaning:'xe taxi', emoji:'🚕', phonemes:[['t','t'],['a','a'],['x','ks'],['i','i']]},
      {word:'México', meaning:'Mexico', emoji:'🇲🇽', phonemes:[['m','m'],['e','e'],['x','x'],['i','i'],['c','k'],['o','o']]},
    ]},
  { id:'ES_Y', label:'y', ipa:'j', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-indigo-700', grad:'from-indigo-700 to-indigo-900', hard:false,
    tip:'Y đầu âm tiết thường đọc như /j/, gần giống "y" trong "yes"',
    words:[
      {word:'ya',   meaning:'rồi/đã',  emoji:'✅', phonemes:[['y','j'],['a','a']]},
      {word:'yema', meaning:'lòng đỏ', emoji:'🥚', phonemes:[['y','j'],['e','e'],['m','m'],['a','a']]},
    ]},
  { id:'ES_Z', label:'z', ipa:'θ / s', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-cyan-700', grad:'from-cyan-700 to-cyan-900', hard:true,
    tip:'Trong cách phát âm Tây Ban Nha (es-ES), Z thường gần /θ/. Ở nhiều nơi khác đọc gần /s/',
    words:[
      {word:'zapato', meaning:'giày', emoji:'👟', phonemes:[['z','θ'],['a','a'],['p','p'],['a','a'],['t','t'],['o','o']]},
      {word:'luz',    meaning:'ánh sáng', emoji:'💡', phonemes:[['l','l'],['u','u'],['z','θ']]},
    ]},
]

export const SPANISH_VOWEL_GROUPS = [
  { key:'Nguyên Âm',     label:'Nguyên Âm · 5 âm thuần' },
  { key:'Nguyên Âm Đôi', label:'Nguyên Âm Đôi · phổ biến' },
]
export const SPANISH_CONSONANT_GROUPS = [
  { key:'Phụ Âm Cơ Bản', label:'Phụ Âm Cơ Bản' },
  { key:'Phụ Âm Đặc Biệt',    label:'Phụ Âm Đặc Biệt ★' },
]

// ─── ITALIAN PHONEME INFO ──────────────────────────────────────────────────
export const ITALIAN_PHONEME_INFO = {
  'a':  { tip: 'Âm "a" thuần — mở miệng rộng, lưỡi thấp. Giống "a" tiếng Việt', hard: false },
  'e':  { tip: 'Âm "ê" — có thể đóng /e/ hoặc mở /ɛ/ tùy từ. Ngắn và rõ ràng', hard: false },
  'ɛ':  { tip: 'Âm "e" mở — miệng hé hơn /e/, giống "e" rõ và ngắn', hard: false },
  'i':  { tip: 'Âm "i" thuần — lưỡi cao phía trước, môi kéo sang ngang', hard: false },
  'o':  { tip: 'Âm "ô" — có thể đóng /o/ hoặc mở /ɔ/ tùy từ', hard: false },
  'ɔ':  { tip: 'Âm "o" mở — môi tròn nhưng miệng mở hơn /o/', hard: false },
  'u':  { tip: 'Âm "u" thuần — môi tròn căng, lưỡi sau', hard: false },
  'r':  { tip: 'Trill r — rung đầu lưỡi vào vòm 1-2 lần. Nhẹ hơn tiếng Tây Ban Nha nhưng vẫn phải rung!', hard: true },
  'ʎ':  { tip: 'Palatal lateral — lưỡi phẳng rộng chạm vòm miệng, âm bên. Như "lj" nói rất nhanh. Không có trong tiếng Việt!', hard: true },
  'ɲ':  { tip: 'Palatal nasal — như "nh" trong tiếng Việt (nhà, nhớ). Dễ với người Việt!', hard: false },
  'ts': { tip: 'Affricate ts — bắt đầu /t/ rồi chuyển ngay sang /s/. Như "c" trong "pizza" đọc "pit-tsa"', hard: true },
  'dz': { tip: 'Affricate dz — bắt đầu /d/ rồi chuyển sang /z/. Biến thể rung của /ts/', hard: true },
  'ʃ':  { tip: 'Âm "sh" — chu môi nhẹ, thổi hơi. Như "sc" trước "e/i" trong tiếng Ý', hard: false },
  'tʃ': { tip: 'Affricate ch — như "ch" tiếng Anh "church". "ci" trước nguyên âm = /tʃ/', hard: false },
  'dʒ': { tip: 'Affricate dj — như "j" tiếng Anh "judge". "gi" trước nguyên âm = /dʒ/', hard: false },
  'n':  { tip: 'Đầu lưỡi chạm sau răng, âm mũi — như "n" tiếng Việt', hard: false },
  'm':  { tip: 'Khép môi, rung âm mũi — như "m" tiếng Việt', hard: false },
  'l':  { tip: 'Đầu lưỡi chạm sau răng trên, âm bên — như "l" tiếng Việt', hard: false },
  'p':  { tip: 'Bật môi không bật hơi — như "p" tiếng Việt', hard: false },
  'b':  { tip: 'Bật môi, rung họng — như "b" tiếng Việt', hard: false },
  't':  { tip: 'Lưỡi chạm sau răng (dental), không bật hơi — như "t" tiếng Việt', hard: false },
  'd':  { tip: 'Lưỡi chạm sau răng, rung họng — như "đ" tiếng Việt', hard: false },
  'k':  { tip: 'Lưỡi chạm vòm mềm, bật ra — như "c/k" tiếng Việt', hard: false },
  'g':  { tip: 'Lưỡi chạm vòm mềm, rung họng — như "g" tiếng Việt', hard: false },
  'f':  { tip: 'Răng trên + môi dưới, thổi khí — như "ph" tiếng Việt', hard: false },
  'v':  { tip: 'Răng trên + môi dưới, rung họng — như "v" tiếng Việt', hard: false },
  's':  { tip: 'Đầu lưỡi gần răng, thổi khí — như "s/x" tiếng Việt', hard: false },
  'z':  { tip: 'Như /s/ nhưng rung họng — như "d" tiếng Việt trong một số thổ ngữ', hard: false },
  'j':  { tip: 'Bán nguyên âm "y" — lưỡi cao phía trước', hard: false },
  'w':  { tip: 'Bán nguyên âm "u" — môi tròn căng', hard: false },
  'ai': { tip: 'Chuỗi /a/ + /i/ — mở miệng cho /a/ rồi đưa lưỡi nhanh lên /i/', hard: false },
  'ja': { tip: 'Bán nguyên âm /j/ lướt nhanh vào /a/, như "ia" trong ciao', hard: false },
  'jo': { tip: 'Bán nguyên âm /j/ lướt nhanh vào /o/, như "io" cuối từ', hard: false },
  'ju': { tip: 'Bán nguyên âm /j/ lướt nhanh vào /u/, như "iu"', hard: false },
  'wo': { tip: 'Bán nguyên âm /w/ lướt nhanh vào /o/, như "uo"', hard: false },
  'kw': { tip: 'Cụm /k/ + /w/ — bật /k/ rồi tròn môi ngay sang /w/', hard: false },
  'gj': { tip: 'Cụm /g/ + /j/ — giữ /g/ cứng rồi lướt nhẹ sang /j/', hard: false },
  'lj': { tip: 'Cụm /l/ + /j/ — đầu lưỡi chạm /l/ rồi lướt nhanh sang /j/', hard: false },
  'dr': { tip: 'Cụm /d/ + rung /r/ — bật /d/ rồi rung đầu lưỡi ngay', hard: true },
  'gr': { tip: 'Cụm /g/ + rung /r/ — bật /g/ rồi chuyển ngay sang /r/', hard: true },
  'sk': { tip: 'Cụm /s/ + /k/ — thổi /s/ rồi bật /k/ rõ', hard: false },
  'skr': { tip: 'Cụm /s/ + /k/ + /r/ — giữ thứ tự âm rõ, không nuốt /r/', hard: true },
}

// ─── ITALIAN SOUNDS ───────────────────────────────────────────────────────
export const ITALIAN_SOUNDS = [
  // ════ NGUYÊN ÂM ═══════════════════════════════════════════
  { id:'IT_A', label:'a', ipa:'a', type:'vowel', group:'Nguyên Âm',
    color:'bg-red-700', grad:'from-red-700 to-red-900', hard:false,
    tip:'Âm "a" thuần — mở miệng rộng, lưỡi thấp. Giống "a" tiếng Việt, ngắn và rõ',
    words:[
      {word:'casa',  meaning:'ngôi nhà', emoji:'🏠', phonemes:[['c','k'],['a','a'],['s','s'],['a','a']]},
      {word:'papa',  meaning:'bố/giáo hoàng', emoji:'👨', phonemes:[['p','p'],['a','a'],['p','p'],['a','a']]},
      {word:'amore', meaning:'tình yêu', emoji:'❤️', phonemes:[['a','a'],['m','m'],['o','o'],['r','r'],['e','e']]},
    ]},
  { id:'IT_E', label:'e', ipa:'e', type:'vowel', group:'Nguyên Âm',
    color:'bg-pink-600', grad:'from-pink-600 to-pink-800', hard:false,
    tip:'Âm "ê" — có thể đóng /e/ hoặc mở /ɛ/ tùy từ. Ngắn và rõ, không trượt như tiếng Anh',
    words:[
      {word:'bene',  meaning:'tốt lắm',  emoji:'👍', phonemes:[['b','b'],['e','e'],['n','n'],['e','e']]},
      {word:'mele',  meaning:'những quả táo', emoji:'🍎', phonemes:[['m','m'],['e','e'],['l','l'],['e','e']]},
      {word:'verde', meaning:'màu xanh lá', emoji:'🟢', phonemes:[['v','v'],['e','ɛ'],['r','r'],['d','d'],['e','e']]},
    ]},
  { id:'IT_I', label:'i', ipa:'i', type:'vowel', group:'Nguyên Âm',
    color:'bg-purple-700', grad:'from-purple-700 to-purple-900', hard:false,
    tip:'Âm "i" thuần — lưỡi cao phía trước. Ngắn và rõ ràng',
    words:[
      {word:'bici',   meaning:'xe đạp', emoji:'🚲', phonemes:[['b','b'],['i','i'],['c','tʃ'],['i','i']]},
      {word:'Italia', meaning:'nước Ý', emoji:'🇮🇹', phonemes:[['i','i'],['t','t'],['a','a'],['li','lj'],['a','a']]},
      {word:'vino',   meaning:'rượu vang', emoji:'🍷', phonemes:[['v','v'],['i','i'],['n','n'],['o','o']]},
    ]},
  { id:'IT_O', label:'o', ipa:'o', type:'vowel', group:'Nguyên Âm',
    color:'bg-teal-600', grad:'from-teal-600 to-teal-800', hard:false,
    tip:'Âm "ô" — môi tròn, lưỡi giữa-sau. Ngắn và thuần, không trượt lên /u/ như tiếng Anh',
    words:[
      {word:'modo',  meaning:'cách thức',emoji:'💡', phonemes:[['m','m'],['o','o'],['d','d'],['o','o']]},
      {word:'foto',  meaning:'bức ảnh', emoji:'📷', phonemes:[['f','f'],['o','ɔ'],['t','t'],['o','o']]},
      {word:'sole',  meaning:'mặt trời', emoji:'☀️', phonemes:[['s','s'],['o','o'],['l','l'],['e','e']]},
    ]},
  { id:'IT_U', label:'u', ipa:'u', type:'vowel', group:'Nguyên Âm',
    color:'bg-cyan-600', grad:'from-cyan-600 to-cyan-800', hard:false,
    tip:'Âm "u" thuần — môi tròn căng, lưỡi sau. Ngắn và rõ hơn /uː/ tiếng Anh',
    words:[
      {word:'tutto', meaning:'tất cả', emoji:'💯', phonemes:[['t','t'],['u','u'],['tt','t'],['o','o']]},
      {word:'uno',   meaning:'số một',   emoji:'1️⃣', phonemes:[['u','u'],['n','n'],['o','o']]},
      {word:'luna',  meaning:'mặt trăng',emoji:'🌙', phonemes:[['l','l'],['u','u'],['n','n'],['a','a']]},
    ]},

  // ════ PHỤ ÂM ĐƠN ══════════════════════════════════════════
  { id:'IT_B', label:'B', ipa:'b', type:'consonant', group:'Phụ Âm Đơn',
    color:'bg-blue-700', grad:'from-blue-700 to-blue-900', hard:false,
    tip:'Bật hai môi và rung dây thanh âm. Tiếng Ý /b/ rõ, không bật hơi mạnh',
    words:[
      {word:'bello',  meaning:'đẹp', emoji:'😍', phonemes:[['b','b'],['e','ɛ'],['ll','l'],['o','o']]},
      {word:'banca',  meaning:'ngân hàng', emoji:'🏦', phonemes:[['b','b'],['a','a'],['n','n'],['c','k'],['a','a']]},
      {word:'bambino',meaning:'em bé', emoji:'👶', phonemes:[['b','b'],['a','a'],['m','m'],['b','b'],['i','i'],['n','n'],['o','o']]},
    ]},
  { id:'IT_CK', label:'C (K)', ipa:'k', type:'consonant', group:'Phụ Âm Đơn',
    color:'bg-orange-700', grad:'from-orange-700 to-orange-900', hard:false,
    tip:'C trước a/o/u hoặc phụ âm đọc /k/. Bật ở vòm mềm, gọn và không bật hơi mạnh',
    words:[
      {word:'casa',  meaning:'ngôi nhà', emoji:'🏠', phonemes:[['c','k'],['a','a'],['s','s'],['a','a']]},
      {word:'cosa',  meaning:'đồ vật/việc', emoji:'📦', phonemes:[['c','k'],['o','ɔ'],['s','s'],['a','a']]},
      {word:'cuore', meaning:'trái tim', emoji:'❤️', phonemes:[['cu','kw'],['o','ɔ'],['r','r'],['e','e']]},
    ]},
  { id:'IT_CCH', label:'C (Ch)', ipa:'tʃ', type:'consonant', group:'Phụ Âm Đơn',
    color:'bg-green-700', grad:'from-green-700 to-green-900', hard:false,
    tip:'"c" trước i/e = /tʃ/ như "ch" tiếng Anh. Lưỡi chạm vòm, mở ra thổi — dễ nhớ!',
    words:[
      {word:'ciao',  meaning:'xin chào',  emoji:'👋', phonemes:[['c','tʃ'],['ia','ja'],['o','o']]},
      {word:'cena',  meaning:'bữa tối',   emoji:'🍽️', phonemes:[['c','tʃ'],['e','e'],['n','n'],['a','a']]},
      {word:'bici',  meaning:'xe đạp', emoji:'🚲', phonemes:[['b','b'],['i','i'],['c','tʃ'],['i','i']]},
    ]},
  { id:'IT_D', label:'D', ipa:'d', type:'consonant', group:'Phụ Âm Đơn',
    color:'bg-amber-700', grad:'from-amber-700 to-amber-900', hard:false,
    tip:'Đầu lưỡi chạm sau răng trên, bật nhẹ và rung họng. Không bật hơi như tiếng Anh',
    words:[
      {word:'dito',  meaning:'ngón tay', emoji:'☝️', phonemes:[['d','d'],['i','i'],['t','t'],['o','o']]},
      {word:'donna', meaning:'phụ nữ', emoji:'👩', phonemes:[['d','d'],['o','ɔ'],['nn','n'],['a','a']]},
      {word:'padre', meaning:'cha/bố', emoji:'👨', phonemes:[['p','p'],['a','a'],['dr','dr'],['e','e']]},
    ]},
  { id:'IT_F', label:'F', ipa:'f', type:'consonant', group:'Phụ Âm Đơn',
    color:'bg-sky-700', grad:'from-sky-700 to-sky-900', hard:false,
    tip:'Răng trên chạm môi dưới, thổi khí không rung họng',
    words:[
      {word:'foto',    meaning:'bức ảnh', emoji:'📷', phonemes:[['f','f'],['o','ɔ'],['t','t'],['o','o']]},
      {word:'famiglia',meaning:'gia đình', emoji:'👨‍👩‍👧', phonemes:[['f','f'],['a','a'],['m','m'],['i','i'],['gli','ʎ'],['a','a']]},
      {word:'fiume',   meaning:'dòng sông', emoji:'🏞️', phonemes:[['f','f'],['iu','ju'],['m','m'],['e','e']]},
    ]},
  { id:'IT_GG', label:'G (G)', ipa:'g', type:'consonant', group:'Phụ Âm Đơn',
    color:'bg-emerald-700', grad:'from-emerald-700 to-emerald-900', hard:false,
    tip:'G trước a/o/u hoặc phụ âm đọc /g/. Lưỡi chạm vòm mềm và rung họng',
    words:[
      {word:'gatto', meaning:'con mèo', emoji:'🐈', phonemes:[['g','g'],['a','a'],['tt','t'],['o','o']]},
      {word:'gola',  meaning:'cổ họng', emoji:'🗣️', phonemes:[['g','g'],['o','o'],['l','l'],['a','a']]},
      {word:'grande',meaning:'to/lớn', emoji:'📏', phonemes:[['gr','gr'],['a','a'],['n','n'],['d','d'],['e','e']]},
    ]},
  { id:'IT_GGI', label:'G (Gi)', ipa:'dʒ', type:'consonant', group:'Phụ Âm Đơn',
    color:'bg-lime-700', grad:'from-lime-700 to-lime-900', hard:false,
    tip:'G trước e/i đọc /dʒ/ như "j" trong "judge". Có rung họng',
    words:[
      {word:'giorno', meaning:'ngày', emoji:'📅', phonemes:[['gi','dʒ'],['o','o'],['r','r'],['n','n'],['o','o']]},
      {word:'gente',  meaning:'người', emoji:'👥', phonemes:[['g','dʒ'],['e','ɛ'],['n','n'],['t','t'],['e','e']]},
      {word:'gelato', meaning:'kem Ý', emoji:'🍨', phonemes:[['g','dʒ'],['e','e'],['l','l'],['a','a'],['t','t'],['o','o']]},
    ]},
  { id:'IT_H', label:'H câm', ipa:'∅', type:'consonant', group:'Phụ Âm Đơn',
    color:'bg-slate-700', grad:'from-slate-700 to-slate-900', hard:false,
    tip:'Chữ h trong tiếng Ý không phát âm. Khi luyện, app chỉ chấm các âm thật phía sau chữ h',
    words:[
      {word:'ho',    meaning:'tôi có', emoji:'✅', phonemes:[['o','o']]},
      {word:'hai',   meaning:'bạn có', emoji:'🫵', phonemes:[['ai','ai']]},
      {word:'hotel', meaning:'khách sạn', emoji:'🏨', phonemes:[['o','o'],['t','t'],['e','ɛ'],['l','l']]},
    ]},
  { id:'IT_L', label:'L', ipa:'l', type:'consonant', group:'Phụ Âm Đơn',
    color:'bg-violet-700', grad:'from-violet-700 to-violet-900', hard:false,
    tip:'Đầu lưỡi chạm sau răng trên, hơi thoát hai bên lưỡi. Luôn rõ, không tối như English dark L',
    words:[
      {word:'luna',  meaning:'mặt trăng', emoji:'🌙', phonemes:[['l','l'],['u','u'],['n','n'],['a','a']]},
      {word:'latte', meaning:'sữa', emoji:'🥛', phonemes:[['l','l'],['a','a'],['tt','t'],['e','e']]},
      {word:'sole',  meaning:'mặt trời', emoji:'☀️', phonemes:[['s','s'],['o','o'],['l','l'],['e','e']]},
    ]},
  { id:'IT_M', label:'M', ipa:'m', type:'consonant', group:'Phụ Âm Đơn',
    color:'bg-fuchsia-700', grad:'from-fuchsia-700 to-fuchsia-900', hard:false,
    tip:'Khép hai môi và cho âm vang qua mũi',
    words:[
      {word:'mano',  meaning:'bàn tay', emoji:'✋', phonemes:[['m','m'],['a','a'],['n','n'],['o','o']]},
      {word:'mamma', meaning:'mẹ', emoji:'👩', phonemes:[['m','m'],['a','a'],['mm','m'],['a','a']]},
      {word:'amore', meaning:'tình yêu', emoji:'❤️', phonemes:[['a','a'],['m','m'],['o','o'],['r','r'],['e','e']]},
    ]},
  { id:'IT_N', label:'N', ipa:'n', type:'consonant', group:'Phụ Âm Đơn',
    color:'bg-indigo-700', grad:'from-indigo-700 to-indigo-900', hard:false,
    tip:'Đầu lưỡi chạm sau răng, âm vang qua mũi',
    words:[
      {word:'nome',  meaning:'tên', emoji:'🏷️', phonemes:[['n','n'],['o','o'],['m','m'],['e','e']]},
      {word:'nave',  meaning:'con tàu', emoji:'🚢', phonemes:[['n','n'],['a','a'],['v','v'],['e','e']]},
      {word:'notte', meaning:'đêm', emoji:'🌙', phonemes:[['n','n'],['o','ɔ'],['tt','t'],['e','e']]},
    ]},
  { id:'IT_P', label:'P', ipa:'p', type:'consonant', group:'Phụ Âm Đơn',
    color:'bg-rose-700', grad:'from-rose-700 to-rose-900', hard:false,
    tip:'Bật hai môi nhưng không bật hơi mạnh. Giữ âm ngắn, chắc',
    words:[
      {word:'pane',  meaning:'bánh mì', emoji:'🍞', phonemes:[['p','p'],['a','a'],['n','n'],['e','e']]},
      {word:'pasta', meaning:'mì Ý', emoji:'🍝', phonemes:[['p','p'],['a','a'],['s','s'],['t','t'],['a','a']]},
      {word:'pizza', meaning:'pizza', emoji:'🍕', phonemes:[['p','p'],['i','i'],['zz','ts'],['a','a']]},
    ]},
  { id:'IT_Q', label:'Q', ipa:'kw', type:'consonant', group:'Phụ Âm Đơn',
    color:'bg-cyan-700', grad:'from-cyan-700 to-cyan-900', hard:false,
    tip:'Q luôn đi với u và đọc /kw/. Bật /k/ rồi tròn môi nhanh sang /w/',
    words:[
      {word:'qui',    meaning:'ở đây', emoji:'📍', phonemes:[['qu','kw'],['i','i']]},
      {word:'quando', meaning:'khi nào', emoji:'⏰', phonemes:[['qu','kw'],['a','a'],['n','n'],['d','d'],['o','o']]},
      {word:'quattro',meaning:'số bốn', emoji:'4️⃣', phonemes:[['qu','kw'],['a','a'],['tt','t'],['r','r'],['o','o']]},
    ]},
  { id:'IT_R', label:'R', ipa:'r', type:'consonant', group:'Phụ Âm Đơn',
    color:'bg-orange-700', grad:'from-orange-700 to-orange-900', hard:true,
    tip:'Trill r — rung đầu lưỡi 1-2 lần vào vòm. Nhẹ hơn tiếng Tây Ban Nha nhưng phải rung. Khác hoàn toàn /r/ tiếng Anh!',
    words:[
      {word:'rosso', meaning:'màu đỏ',   emoji:'🔴', phonemes:[['r','r'],['o','o'],['ss','s'],['o','o']]},
      {word:'raro',  meaning:'hiếm gặp', emoji:'💎', phonemes:[['r','r'],['a','a'],['r','r'],['o','o']]},
      {word:'terra', meaning:'đất đai',  emoji:'🌍', phonemes:[['t','t'],['e','e'],['rr','r'],['a','a']]},
    ]},
  { id:'IT_S', label:'S', ipa:'s', type:'consonant', group:'Phụ Âm Đơn',
    color:'bg-yellow-700', grad:'from-yellow-700 to-yellow-900', hard:false,
    tip:'Đầu lưỡi gần răng, thổi khí. Giữa hai nguyên âm có thể rung thành /z/',
    words:[
      {word:'sole', meaning:'mặt trời', emoji:'☀️', phonemes:[['s','s'],['o','o'],['l','l'],['e','e']]},
      {word:'sala', meaning:'phòng', emoji:'🛋️', phonemes:[['s','s'],['a','a'],['l','l'],['a','a']]},
      {word:'casa', meaning:'ngôi nhà', emoji:'🏠', phonemes:[['c','k'],['a','a'],['s','z'],['a','a']]},
    ]},
  { id:'IT_T', label:'T', ipa:'t', type:'consonant', group:'Phụ Âm Đơn',
    color:'bg-teal-700', grad:'from-teal-700 to-teal-900', hard:false,
    tip:'Đầu lưỡi chạm sau răng trên, bật ngắn và không bật hơi mạnh',
    words:[
      {word:'tavolo', meaning:'cái bàn', emoji:'🪑', phonemes:[['t','t'],['a','a'],['v','v'],['o','o'],['l','l'],['o','o']]},
      {word:'tutto',  meaning:'tất cả', emoji:'💯', phonemes:[['t','t'],['u','u'],['tt','t'],['o','o']]},
      {word:'notte',  meaning:'đêm', emoji:'🌙', phonemes:[['n','n'],['o','ɔ'],['tt','t'],['e','e']]},
    ]},
  { id:'IT_V', label:'V', ipa:'v', type:'consonant', group:'Phụ Âm Đơn',
    color:'bg-purple-700', grad:'from-purple-700 to-purple-900', hard:false,
    tip:'Răng trên chạm môi dưới và rung họng. Khác /f/ vì có rung',
    words:[
      {word:'vino', meaning:'rượu vang', emoji:'🍷', phonemes:[['v','v'],['i','i'],['n','n'],['o','o']]},
      {word:'voce', meaning:'giọng nói', emoji:'🎤', phonemes:[['v','v'],['o','ɔ'],['c','tʃ'],['e','e']]},
      {word:'verde',meaning:'màu xanh lá', emoji:'🟢', phonemes:[['v','v'],['e','ɛ'],['r','r'],['d','d'],['e','e']]},
    ]},
  { id:'IT_Z', label:'Z', ipa:'ts', type:'consonant', group:'Phụ Âm Đơn',
    color:'bg-amber-700', grad:'from-amber-700 to-amber-900', hard:true,
    tip:'Z đọc /ts/ hoặc /dz/. Bắt đầu bằng âm bật rồi chuyển ngay sang âm xát',
    words:[
      {word:'pizza',  meaning:'pizza',    emoji:'🍕', phonemes:[['p','p'],['i','i'],['zz','ts'],['a','a']]},
      {word:'zero',   meaning:'số không', emoji:'0️⃣', phonemes:[['z','dz'],['e','e'],['r','r'],['o','o']]},
      {word:'forza',  meaning:'sức mạnh', emoji:'💪', phonemes:[['f','f'],['o','o'],['r','r'],['z','ts'],['a','a']]},
    ]},

  // ════ TỔ HỢP ÂM ĐẶC BIỆT ══════════════════════════════════
  { id:'IT_CH', label:'CH (K)', ipa:'k', type:'consonant', group:'Tổ Hợp Âm Đặc Biệt',
    color:'bg-red-800', grad:'from-red-800 to-red-950', hard:false,
    tip:'CH trước e/i giữ âm /k/. Chữ h chỉ làm cứng âm c, không đọc riêng',
    words:[
      {word:'che',     meaning:'cái gì/rằng', emoji:'❓', phonemes:[['ch','k'],['e','e']]},
      {word:'chi',     meaning:'ai', emoji:'❓', phonemes:[['ch','k'],['i','i']]},
      {word:'macchina',meaning:'xe hơi', emoji:'🚗', phonemes:[['m','m'],['a','a'],['cch','k'],['i','i'],['n','n'],['a','a']]},
    ]},
  { id:'IT_GH', label:'GH (G)', ipa:'g', type:'consonant', group:'Tổ Hợp Âm Đặc Biệt',
    color:'bg-green-800', grad:'from-green-800 to-green-950', hard:false,
    tip:'GH trước e/i giữ âm /g/. Chữ h làm cứng âm g, không đọc riêng',
    words:[
      {word:'ghe',    meaning:'âm ghe', emoji:'🗣️', phonemes:[['gh','g'],['e','e']]},
      {word:'ghiaccio',meaning:'băng/đá', emoji:'🧊', phonemes:[['ghi','gj'],['a','a'],['cc','tʃ'],['io','jo']]},
      {word:'spaghetti',meaning:'mì spaghetti', emoji:'🍝', phonemes:[['s','s'],['p','p'],['a','a'],['gh','g'],['e','e'],['tt','t'],['i','i']]},
    ]},
  { id:'IT_GN', label:'GN', ipa:'ɲ', type:'consonant', group:'Tổ Hợp Âm Đặc Biệt',
    color:'bg-violet-700', grad:'from-violet-700 to-violet-900', hard:false,
    tip:'"gn" = /ɲ/ — như "nh" trong tiếng Việt. Lưỡi chạm vòm giữa + âm mũi',
    words:[
      {word:'bagno',   meaning:'phòng tắm',emoji:'🚿', phonemes:[['b','b'],['a','a'],['gn','ɲ'],['o','o']]},
      {word:'ogni',    meaning:'mỗi',      emoji:'🔄', phonemes:[['o','o'],['gn','ɲ'],['i','i']]},
      {word:'gnocchi', meaning:'gnocchi',  emoji:'🍝', phonemes:[['gn','ɲ'],['o','ɔ'],['cc','k'],['hi','i']]},
    ]},
  { id:'IT_GLI', label:'GLI', ipa:'ʎ', type:'consonant', group:'Tổ Hợp Âm Đặc Biệt',
    color:'bg-rose-700', grad:'from-rose-700 to-rose-900', hard:true,
    tip:'Palatal lateral — lưỡi rộng phẳng chạm vòm giữa, âm bên. Như "lj" nói rất nhanh. Không có trong tiếng Việt!',
    words:[
      {word:'figlio', meaning:'con trai', emoji:'👦', phonemes:[['f','f'],['i','i'],['gli','ʎ'],['o','o']]},
      {word:'meglio', meaning:'tốt hơn', emoji:'⬆️', phonemes:[['m','m'],['e','e'],['gli','ʎ'],['o','o']]},
      {word:'luglio', meaning:'tháng 7', emoji:'📅', phonemes:[['l','l'],['u','u'],['gli','ʎ'],['o','o']]},
    ]},
  { id:'IT_SC_SK', label:'SC (Sk)', ipa:'sk', type:'consonant', group:'Tổ Hợp Âm Đặc Biệt',
    color:'bg-blue-800', grad:'from-blue-800 to-blue-950', hard:false,
    tip:'SC trước a/o/u hoặc phụ âm đọc /sk/. Giữ /s/ rồi bật /k/',
    words:[
      {word:'scala',  meaning:'cầu thang', emoji:'🪜', phonemes:[['sc','sk'],['a','a'],['l','l'],['a','a']]},
      {word:'scuola', meaning:'trường học', emoji:'🏫', phonemes:[['sc','sk'],['uo','wo'],['l','l'],['a','a']]},
      {word:'scrivo', meaning:'tôi viết', emoji:'✍️', phonemes:[['scr','skr'],['i','i'],['v','v'],['o','o']]},
    ]},
  { id:'IT_SC_SH', label:'SC (Sh)', ipa:'ʃ', type:'consonant', group:'Tổ Hợp Âm Đặc Biệt',
    color:'bg-blue-700', grad:'from-blue-700 to-blue-900', hard:false,
    tip:'SC trước e/i = /ʃ/. Chu môi nhẹ, thổi hơi qua như "sh"',
    words:[
      {word:'pesce',  meaning:'con cá',   emoji:'🐟', phonemes:[['p','p'],['e','e'],['sc','ʃ'],['e','e']]},
      {word:'scena',  meaning:'cảnh/sân khấu',emoji:'🎭', phonemes:[['sc','ʃ'],['e','ɛ'],['n','n'],['a','a']]},
      {word:'uscire', meaning:'ra ngoài', emoji:'🚪', phonemes:[['u','u'],['sc','ʃ'],['i','i'],['r','r'],['e','e']]},
    ]},

  // ════ PHỤ ÂM KÉP ══════════════════════════════════════════
  { id:'IT_TT', label:'TT', ipa:'t', type:'consonant', group:'Phụ Âm Kép',
    color:'bg-stone-700', grad:'from-stone-700 to-stone-900', hard:true,
    tip:'Phụ âm kép giữ lâu hơn phụ âm đơn: chặn /t/ ngắn rồi bật rõ, như có một nhịp dừng nhỏ',
    words:[
      {word:'notte',  meaning:'đêm', emoji:'🌙', phonemes:[['n','n'],['o','ɔ'],['tt','t'],['e','e']]},
      {word:'tutto',  meaning:'tất cả', emoji:'💯', phonemes:[['t','t'],['u','u'],['tt','t'],['o','o']]},
      {word:'gatto',  meaning:'con mèo', emoji:'🐈', phonemes:[['g','g'],['a','a'],['tt','t'],['o','o']]},
    ]},
  { id:'IT_LL', label:'LL', ipa:'l', type:'consonant', group:'Phụ Âm Kép',
    color:'bg-zinc-700', grad:'from-zinc-700 to-zinc-900', hard:true,
    tip:'Giữ /l/ lâu hơn phụ âm đơn. Đầu lưỡi ở sau răng trên thêm một nhịp trước nguyên âm sau',
    words:[
      {word:'bello', meaning:'đẹp', emoji:'😍', phonemes:[['b','b'],['e','ɛ'],['ll','l'],['o','o']]},
      {word:'palla', meaning:'quả bóng', emoji:'⚽', phonemes:[['p','p'],['a','a'],['ll','l'],['a','a']]},
      {word:'colla', meaning:'keo dán', emoji:'🧴', phonemes:[['c','k'],['o','ɔ'],['ll','l'],['a','a']]},
    ]},
  { id:'IT_CC', label:'CC', ipa:'k', type:'consonant', group:'Phụ Âm Kép',
    color:'bg-neutral-700', grad:'from-neutral-700 to-neutral-900', hard:true,
    tip:'CC trước a/o/u hoặc h+i/e là /k/ kép. Giữ chặn /k/ lâu hơn rồi bật rõ',
    words:[
      {word:'bocca',   meaning:'cái miệng', emoji:'👄', phonemes:[['b','b'],['o','ɔ'],['cc','k'],['a','a']]},
      {word:'occhio',  meaning:'con mắt', emoji:'👁️', phonemes:[['o','ɔ'],['cch','k'],['io','jo']]},
      {word:'gnocchi', meaning:'gnocchi', emoji:'🍝', phonemes:[['gn','ɲ'],['o','ɔ'],['cc','k'],['hi','i']]},
    ]},
]

export const ITALIAN_VOWEL_GROUPS    = [{ key:'Nguyên Âm',         label:'Nguyên Âm · 5 âm thuần' }]
export const ITALIAN_CONSONANT_GROUPS = [
  { key:'Phụ Âm Đơn', label:'Phụ Âm Đơn' },
  { key:'Tổ Hợp Âm Đặc Biệt', label:'Tổ Hợp Âm Đặc Biệt ★' },
  { key:'Phụ Âm Kép', label:'Phụ Âm Kép' },
]

// ─── FRENCH PHONEME INFO ───────────────────────────────────────────────────
export const FRENCH_PHONEME_INFO = {
  'y':  { tip: '"u" Pháp — môi tròn căng như /u/ nhưng lưỡi đặt cao phía trước như /i/. Không có trong tiếng Việt! Tập: nói /i/ rồi tròn môi lại', hard: true },
  'ø':  { tip: '"eu" fermé — môi tròn vừa, lưỡi giữa-cao. Như /e/ nhưng tròn môi. "eu/oeu" trong "bleu, yeux"', hard: true },
  'œ':  { tip: '"eu" ouvert — môi tròn, miệng hé hơn /ø/. Như /ɛ/ nhưng tròn môi. "eu/oeu" trước phụ âm cuối', hard: true },
  'ɑ̃':  { tip: 'Nguyên âm mũi an/en — âm "a" ngân qua mũi, không đóng môi. "an, en, am, em" trong tiếng Pháp', hard: true },
  'ɛ̃':  { tip: 'Nguyên âm mũi in/ain — âm "e" mở ngân qua mũi. "in, ain, im, aim, yn" trong tiếng Pháp', hard: true },
  'ɔ̃':  { tip: 'Nguyên âm mũi on — âm "o" mở ngân qua mũi. "on, om" trong tiếng Pháp', hard: true },
  'wa': { tip: '"oi" = /wa/ — "w" trượt sang "a". Không đọc là "oa" hay "oai"! "oi" trong tiếng Pháp luôn = /wa/', hard: false },
  'ɥ':  { tip: 'Bán nguyên âm "u" Pháp — môi tròn như /y/ nhưng nhanh, trước nguyên âm. "ui, nu+vowel"', hard: true },
  'ʁ':  { tip: 'R uvulaire — rung cuống lưỡi (phía sau cổ họng), không phải đầu lưỡi. Như tiếng gargle nhẹ. Khó nhất tiếng Pháp!', hard: true },
  'ʃ':  { tip: '"ch" Pháp — chu môi nhẹ, thổi hơi. Như "sh" tiếng Anh. "chat, chapeau" = /ʃ/', hard: false },
  'ʒ':  { tip: '"j/ge" Pháp — như "sh" nhưng rung họng. Như "s" trong "measure" tiếng Anh. "jaune, jupe" = /ʒ/', hard: false },
  'j':  { tip: 'Bán nguyên âm "y" — lưỡi cao phía trước. "ill, ille, y" trong tiếng Pháp = /j/ (như "y" trong "yes")', hard: false },
  'ɛ':  { tip: '"è/ê/ai" — âm "e" mở, miệng hé vừa. "è, ê, ai, ei, et(cuối)" trong tiếng Pháp', hard: false },
  'e':  { tip: '"é" — âm "e" đóng, lưỡi cao, môi kéo nhẹ. "é, er(cuối), ez(cuối)"', hard: false },
  'ə':  { tip: 'Schwa — âm trung hòa ngắn. "e" không dấu trong tiếng Pháp', hard: false },
  'u':  { tip: '"ou" = /u/ — môi tròn căng. "ou" trong tiếng Pháp luôn = /u/, KHÔNG phải /ou/ như tiếng Anh!', hard: false },
  'o':  { tip: '"o/ô/au/eau" = /o/ — môi tròn vừa, âm đóng. "eau" luôn đọc là /o/ trong tiếng Pháp', hard: false },
  'ɔ':  { tip: '"o" mở — miệng hé hơn /o/. "o" trước phụ âm phát âm trong từ đơn tiết', hard: false },
  'a':  { tip: 'Âm "a" — mở miệng, lưỡi thấp. Như "a" tiếng Việt', hard: false },
  'p':  { tip: 'Bật môi không bật hơi', hard: false },
  'b':  { tip: 'Bật môi, rung họng', hard: false },
  't':  { tip: 'Lưỡi chạm sau răng, không bật hơi', hard: false },
  'd':  { tip: 'Lưỡi chạm sau răng, rung họng', hard: false },
  'k':  { tip: 'Lưỡi chạm vòm mềm, bật ra', hard: false },
  'g':  { tip: 'Lưỡi chạm vòm mềm, rung họng', hard: false },
  'f':  { tip: 'Răng trên + môi dưới, thổi khí', hard: false },
  'v':  { tip: 'Răng trên + môi dưới, rung họng', hard: false },
  's':  { tip: 'Đầu lưỡi gần răng, thổi khí', hard: false },
  'z':  { tip: 'Như /s/ nhưng rung họng', hard: false },
  'l':  { tip: 'Đầu lưỡi chạm sau răng trên, âm bên', hard: false },
  'n':  { tip: 'Đầu lưỡi chạm sau răng, âm mũi', hard: false },
  'm':  { tip: 'Khép môi, rung âm mũi', hard: false },
  'bl': { tip: '/b/ + /l/ kết hợp', hard: false },
  'bʁ': { tip: '/b/ + /ʁ/ — r uvulaire sau b', hard: true },
  'fʁ': { tip: '/f/ + /ʁ/ — r uvulaire sau f', hard: true },
  'bl': { tip: '/b/ + /l/', hard: false },
}

// ─── FRENCH SOUNDS (12 âm) ────────────────────────────────────────────────
// Từ vựng: màu sắc, động vật, trái cây, quần áo, đồ chơi, cơ thể
export const FRENCH_SOUNDS = [
  // ════ NGUYÊN ÂM ĐẶC BIỆT ════════════════════════════════════
  { id:'FR_Y', label:'u', ipa:'y', type:'vowel', group:'Nguyên Âm Đặc Biệt',
    color:'bg-red-700', grad:'from-red-700 to-red-900', hard:true,
    tip:'"u" Pháp — môi tròn như /u/ nhưng lưỡi cao phía trước như /i/. Không có trong tiếng Việt! Tập: nói /i/ rồi tròn môi',
    words:[
      {word:'jupe',    meaning:'váy đầm',   emoji:'👗', phonemes:[['j','ʒ'],['u','y'],['pe','p']]},
      {word:'tortue',  meaning:'con rùa',   emoji:'🐢', phonemes:[['t','t'],['or','ɔʁ'],['tue','ty']]},
      {word:'culotte', meaning:'quần lót',  emoji:'👙', phonemes:[['c','k'],['u','y'],['lotte','lɔt']]},
    ]},
  { id:'FR_EU', label:'eu', ipa:'ø', type:'vowel', group:'Nguyên Âm Đặc Biệt',
    color:'bg-pink-600', grad:'from-pink-600 to-pink-800', hard:true,
    tip:'"eu" — môi tròn vừa, lưỡi giữa-cao. Như /e/ nhưng tròn môi lại. "bleu, yeux, cheveux"',
    words:[
      {word:'bleu',    meaning:'màu xanh dương',emoji:'🔵', phonemes:[['bl','bl'],['eu','ø']]},
      {word:'yeux',    meaning:'đôi mắt',    emoji:'👀', phonemes:[['y','j'],['eux','ø']]},
      {word:'cheveux', meaning:'mái tóc',    emoji:'💇', phonemes:[['ch','ʃ'],['e','ə'],['v','v'],['eux','ø']]},
    ]},
  { id:'FR_AN', label:'an', ipa:'ɑ̃', type:'vowel', group:'Nguyên Âm Đặc Biệt',
    color:'bg-purple-700', grad:'from-purple-700 to-purple-900', hard:true,
    tip:'Nguyên âm mũi an/en — âm "a" ngân qua mũi, không đóng môi cuối. "an, en, am, em" trong tiếng Pháp',
    words:[
      {word:'pantalon', meaning:'quần dài',  emoji:'👖', phonemes:[['p','p'],['an','ɑ̃'],['t','t'],['a','a'],['l','l'],['on','ɔ̃']]},
      {word:'blanc',    meaning:'màu trắng', emoji:'⬜', phonemes:[['bl','bl'],['anc','ɑ̃']]},
      {word:'jambes',   meaning:'đôi chân',  emoji:'🦵', phonemes:[['j','ʒ'],['am','ɑ̃'],['bes','b']]},
    ]},
  { id:'FR_IN', label:'in', ipa:'ɛ̃', type:'vowel', group:'Nguyên Âm Đặc Biệt',
    color:'bg-indigo-700', grad:'from-indigo-700 to-indigo-900', hard:true,
    tip:'Nguyên âm mũi in/ain — âm "e" mở ngân qua mũi. "in, ain, im, aim" trong tiếng Pháp. Không đóng cuối bằng /n/!',
    words:[
      {word:'lapin',  meaning:'con thỏ',    emoji:'🐰', phonemes:[['l','l'],['a','a'],['p','p'],['in','ɛ̃']]},
      {word:'mains',  meaning:'đôi tay',    emoji:'🙌', phonemes:[['m','m'],['ains','ɛ̃']]},
      {word:'bain',   meaning:'bồn tắm',    emoji:'🛁', phonemes:[['b','b'],['ain','ɛ̃']]},
    ]},
  { id:'FR_ON', label:'on', ipa:'ɔ̃', type:'vowel', group:'Nguyên Âm Đặc Biệt',
    color:'bg-teal-600', grad:'from-teal-600 to-teal-800', hard:true,
    tip:'Nguyên âm mũi on — âm "o" mở ngân qua mũi. "on, om" trong tiếng Pháp. Khác "ong" tiếng Việt: không đóng môi!',
    words:[
      {word:'ballon',  meaning:'quả bóng',  emoji:'🎈', phonemes:[['b','b'],['a','a'],['ll','l'],['on','ɔ̃']]},
      {word:'poisson', meaning:'con cá',    emoji:'🐟', phonemes:[['p','p'],['oi','wa'],['ss','s'],['on','ɔ̃']]},
      {word:'pantalon',meaning:'quần dài',  emoji:'👖', phonemes:[['p','p'],['an','ɑ̃'],['t','t'],['a','a'],['l','l'],['on','ɔ̃']]},
    ]},
  { id:'FR_OI', label:'oi', ipa:'wa', type:'vowel', group:'Nguyên Âm Đặc Biệt',
    color:'bg-cyan-600', grad:'from-cyan-600 to-cyan-800', hard:false,
    tip:'"oi" = /wa/ — /w/ trượt nhanh sang /a/. KHÔNG đọc là "oa" hay "oai"! Luôn là /wa/ trong tiếng Pháp',
    words:[
      {word:'voiture', meaning:'xe hơi',    emoji:'🚗', phonemes:[['v','v'],['oi','wa'],['t','t'],['u','y'],['re','ʁ']]},
      {word:'noir',    meaning:'màu đen',   emoji:'⬛', phonemes:[['n','n'],['oi','wa'],['r','ʁ']]},
      {word:'oiseau',  meaning:'con chim',  emoji:'🐦', phonemes:[['oi','wa'],['s','z'],['eau','o']]},
    ]},
  // ════ PHỤ ÂM ĐẶC BIỆT ═══════════════════════════════════════
  { id:'FR_R', label:'r', ipa:'ʁ', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-orange-700', grad:'from-orange-700 to-orange-900', hard:true,
    tip:'R uvulaire — rung cuống lưỡi ở cổ họng phía sau, KHÔNG phải đầu lưỡi. Như tiếng gargle nhẹ. Khó nhất tiếng Pháp!',
    words:[
      {word:'rouge',  meaning:'màu đỏ',    emoji:'🔴', phonemes:[['r','ʁ'],['ou','u'],['ge','ʒ']]},
      {word:'robot',  meaning:'rô-bốt',    emoji:'🤖', phonemes:[['r','ʁ'],['o','ɔ'],['b','b'],['ot','o']]},
      {word:'bras',   meaning:'cánh tay',  emoji:'💪', phonemes:[['br','bʁ'],['as','a']]},
    ]},
  { id:'FR_CH', label:'ch', ipa:'ʃ', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-amber-600', grad:'from-amber-600 to-amber-800', hard:false,
    tip:'"ch" Pháp = /ʃ/ — chu môi nhẹ, thổi hơi. Như "sh" tiếng Anh "shoe". KHÔNG phải "ch" tiếng Anh "church"!',
    words:[
      {word:'chat',       meaning:'con mèo',   emoji:'🐱', phonemes:[['ch','ʃ'],['at','a']]},
      {word:'chapeau',    meaning:'cái mũ',    emoji:'👒', phonemes:[['ch','ʃ'],['a','a'],['p','p'],['eau','o']]},
      {word:'chaussettes',meaning:'đôi vớ',    emoji:'🧦', phonemes:[['ch','ʃ'],['aus','o'],['settes','sɛt']]},
    ]},
  { id:'FR_J', label:'j', ipa:'ʒ', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-rose-700', grad:'from-rose-700 to-rose-900', hard:false,
    tip:'"j/ge" Pháp = /ʒ/ — như "sh" nhưng rung họng. Như "s" trong "measure, vision" tiếng Anh. "jaune, jupe, jambe"',
    words:[
      {word:'jaune',  meaning:'màu vàng',  emoji:'🟡', phonemes:[['j','ʒ'],['au','o'],['ne','n']]},
      {word:'jupe',   meaning:'váy đầm',   emoji:'👗', phonemes:[['j','ʒ'],['u','y'],['pe','p']]},
      {word:'jambes', meaning:'đôi chân',  emoji:'🦵', phonemes:[['j','ʒ'],['am','ɑ̃'],['bes','b']]},
    ]},
  { id:'FR_UI', label:'ui', ipa:'ɥ', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-violet-700', grad:'from-violet-700 to-violet-900', hard:true,
    tip:'Bán nguyên âm /ɥ/ — môi tròn như /y/ nhưng rất ngắn, trước nguyên âm. "nuit" = /nɥi/. Khó vì không có trong tiếng Việt!',
    words:[
      {word:'nuit',  meaning:'ban đêm',   emoji:'🌙', phonemes:[['n','n'],['uit','ɥi']]},
      {word:'lui',   meaning:'anh ấy',    emoji:'🧑', phonemes:[['l','l'],['ui','ɥi']]},
      {word:'fruit', meaning:'trái cây',  emoji:'🍎', phonemes:[['fr','fʁ'],['uit','ɥi']]},
    ]},
  { id:'FR_ILL', label:'ill', ipa:'j', type:'consonant', group:'Phụ Âm Đặc Biệt',
    color:'bg-emerald-700', grad:'from-emerald-700 to-emerald-900', hard:false,
    tip:'"ill/ille/y" = /j/ — như "y" trong tiếng Anh "yes". "oreilles, maillot, yeux" đều có /j/. KHÔNG phải /l/ hay /ɪl/!',
    words:[
      {word:'oreilles', meaning:'đôi tai',   emoji:'👂', phonemes:[['o','ɔ'],['r','ʁ'],['eilles','ɛj']]},
      {word:'maillot',  meaning:'áo bơi',    emoji:'🩱', phonemes:[['m','m'],['aill','aj'],['ot','o']]},
      {word:'yeux',     meaning:'đôi mắt',   emoji:'👀', phonemes:[['y','j'],['eux','ø']]},
    ]},
  { id:'FR_E', label:'è/ê', ipa:'ɛ', type:'vowel', group:'Nguyên Âm Đặc Biệt',
    color:'bg-blue-700', grad:'from-blue-700 to-blue-900', hard:false,
    tip:'"è/ê/ai" = /ɛ/ — âm "e" mở, miệng hé vừa. "tête, raisin, casquette" đều có /ɛ/. Khác /e/ đóng trong "é"',
    words:[
      {word:'tête',     meaning:'cái đầu',   emoji:'🗣️', phonemes:[['t','t'],['ête','ɛt']]},
      {word:'casquette',meaning:'mũ lưỡi trai',emoji:'🧢', phonemes:[['c','k'],['as','as'],['qu','k'],['ette','ɛt']]},
      {word:'raisin',   meaning:'nho',        emoji:'🍇', phonemes:[['r','ʁ'],['ai','ɛ'],['s','z'],['in','ɛ̃']]},
    ]},
]

export const FRENCH_VOWEL_GROUPS    = [{ key:'Nguyên Âm Đặc Biệt', label:'Nguyên Âm Đặc Biệt ★' }]
export const FRENCH_CONSONANT_GROUPS = [{ key:'Phụ Âm Đặc Biệt',  label:'Phụ Âm Đặc Biệt ★' }]
